(()=>{
'use strict';
// Meridian City: where residents meet. One flat chart with a plaza and venues in the open, towers around it and a
// stair to a rooftop. Every social act is a ledger record (chat, posts, meetups, scores, dances, songs, fireworks,
// avatars), so importing another resident's ledger brings their words, their scores and a silhouette of them that
// walks to where they were last. Physics is real where it is felt: the crowd is a Kuramoto system your feet are coupled
// to, a cup cools by Newton's law, a firework flies against quadratic drag, the echo room obeys Sabine, and the
// silhouettes move on a critically damped second-order servo.
const M=window.REALITI_MATRIX_V1,MW=window.REALITI_MATRIX_WORLD_V1,DYN=window.REALITI_DYNAMICS_V1,AR=window.REALITI_ARCHIPELAGO_V1,LG=window.REALITI_LEDGER_V1,CAT=window.REALITI_CATNIP_V1,LGM=window.REALITI_LONG_GAME_V1;if(!M||!MW||!DYN||!AR||!LG||!CAT||!LGM)return;
const CITY='MERIDIAN_CITY',now=()=>Number(C9?.b7?.clock||0),room=()=>C9?.currentRoom,cp=x=>JSON.parse(JSON.stringify(x)),TAU=2*Math.PI,T=LGM.T;
const me=()=>M.state().residents['resident:self'],observer=()=>String(C9?.verticalContinuity?.observer||'local'),ent=()=>M.entities(),records=()=>(C9.ledger?.records||[]),mine=e=>e.by===observer(),by8=e=>String(e.by).slice(0,8);
const dist2=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const near=(id,tol=1.5)=>{const e=ent()[id],r=me();return !!(e&&r&&r.chart===CITY&&Math.max(0,M.sdf(e,r.pose.position))<=tol)};
function S(){const w=(C9.chapter2=C9.chapter2||{v:1});w.city=w.city||{venue:null,lastArrive:-1e9,dance:{on:false,bpm:0,theta:0,until:0,best:1e9},cup:null,sips:0,arcade:{round:0,seq:[],score:0,best:0},ghosts:{},size:'normal'};return w.city}
for(const [id,text] of Object.entries({on_the_beat:'Your feet found the house tempo within two beats a minute while the floor was in phase.',floor_is_one:'The whole floor locked: order above 0.95 with four or more dancing.',warm_hands:'Three sips before the cup fell under forty degrees.',arcade_ten:'Ten in a row on the pattern wall.',top_of_the_board:'Your name is at the top of the leaderboard.',sabine:'You sang in the echo room and heard how long the hall holds a note.',first_post:'You left a post on the Commons wall.',rooftop_view:'You climbed thirty steps to the roof.',firework:'A rocket you launched burst over the plaza.',met_up:'You were at a meetup within two minutes of another resident. Asynchronous, but real.',new_face:'You chose a name and a form. The ledger knows you by them.',regular:'Five arrivals in Meridian City.'}))CAT.register(id,text);

// Chart: 160 m square, a plaza in the open, towers around it, a stair of thirty 0.4 m steps to the roof of the east tower.
M.define(CITY,{bounds:{kind:'BOX',center:[0,0,20],halfExtents:[80,80,20]},spawn:{position:[0,-24,.85],rotation:[0,0,0,1]},view:30,stride:60,tags:['city','outdoors']});
M.addEntity({id:'city.ground',chart:CITY,position:[0,0,-.5],shape:{kind:'BOX',halfExtents:[80,80,.5]},tags:['floor','structure','stone'],collision:true,material:'ceramic',label:'paving'});
for(const [k,x,y,hx,hy] of [['east',80.5,0,.5,81],['west',-80.5,0,.5,81],['north',0,80.5,81,.5],['south',0,-80.5,81,.5]])M.addEntity({id:`city.edge.${k}`,chart:CITY,position:[x,y,20],shape:{kind:'BOX',halfExtents:[hx,hy,20]},tags:['edge','structure'],collision:true,label:'the edge of the city'});
const TOWERS=[[60,60,6,'east tower'],[-60,60,10,'north-west tower'],[-60,-60,8,'south-west tower'],[60,-60,12,'south-east tower'],[0,65,5,'north hall'],[-65,0,7,'west hall'],[65,0,7,'east hall'],[0,-65,4,'south hall']];
TOWERS.forEach(([x,y,hz,label],i)=>M.addEntity({id:`city.${label.replace(/\s+/g,'_')}`,chart:CITY,position:[x,y,hz],shape:{kind:'BOX',halfExtents:[10,10,hz]},tags:['building','structure','landmark'],collision:true,material:'ceramic',label}));
for(let i=0;i<30;i++){const top=(i+1)*.4;M.addEntity({id:`city.stair_${i+1}`,chart:CITY,position:[60,35.25+.5*i,top/2],shape:{kind:'BOX',halfExtents:[1.5,.25,top/2]},tags:['step','support','structure','stair'],collision:true,material:'ceramic',label:`stair step ${i+1}`})}
const VENUES={commons:{at:[0,0],r:18,label:'the Commons'},dancehall:{at:[36,0],r:9,label:'the Dancehall'},teahouse:{at:[-36,0],r:8,label:'the Teahouse'},arcade:{at:[0,-36],r:8,label:'the Arcade'},echo:{at:[0,36],r:8,label:'the Echo Room'},roof:{at:[60,60],r:9,label:'the Rooftop',z:12}};
for(const [k,v] of Object.entries(VENUES))M.addEntity({id:`venue.${k}`,chart:CITY,position:[v.at[0],v.at[1],(v.z||0)+2],shape:{kind:'VOLUME',halfExtents:[v.r,v.r,2]},tags:['venue','landmark',k],collision:false,material:null,label:v.label,affordances:[]});
for(const [id,kind,pos,size,tags,material,aff,label] of [['commons.fountain','SPHERE',[0,0,1.2],1.6,['fountain','water','landmark'],'ceramic',['toss'],'fountain'],['commons.wall','BOX',[0,19,1.3],[4,.2,1.3],['wall','board','landmark'],'ceramic',['read','post'],'message wall'],['dancehall.speaker','BOX',[36,8,1],[.6,.6,1],['speaker','music'],'wood',['listen'],'speaker stack'],['teahouse.counter','BOX',[-36,-6,.5],[3,.5,.5],['counter','wood','support'],'wood',['order'],'tea counter'],['teahouse.bench','BOX',[-40,0,.25],[1.2,.4,.25],['bench','support'],'wood',['sit'],'teahouse bench'],['arcade.wall','BOX',[0,-43,1.4],[2,.15,1.2],['wall','lights','game'],'glass',['play'],'pattern wall'],['echo.stage','BOX',[0,42,.2],[3,2,.2],['stage','support'],'wood',['sing','sit'],'stage'],['roof.rail','BOX',[60,69.5,12.5],[9.5,.1,.5],['rail','metal'],'metal',['lean'],'roof rail'],['roof.mortar','BOX',[64,64,12.3],[.3,.3,.3],['mortar','fireworks'],'metal',['launch'],'firework mortar']])M.addEntity({id,chart:CITY,position:pos,shape:kind==='SPHERE'?{kind,radius:size}:{kind,halfExtents:size},tags,collision:true,material,affordances:aff,label});
M.definePortal({id:'cloud_nine_nest.to.meridian_city',from:'CLOUD_NINE_NEST',to:CITY,entry:[4.5,-4.5,.85],exit:[0,-26,.85],label:'the lift down to Meridian City'});
M.definePortal({id:'meridian_city.to.cloud_nine_nest',from:CITY,to:'CLOUD_NINE_NEST',entry:[-6,-26,.85],exit:[0,4.4,.85],label:'the lift home to Cloud Nine Nest'});
M.definePortal({id:'meridian_city.to.archipelago',from:CITY,to:AR.chart,entry:[6,-26,.85],exit:[6,AR.shore_y+30,AR.h(6,AR.shore_y+30)+.85],label:'the harbor tram to the Archipelago'});
const venueAt=(x,y)=>{let best=null;for(const [k,v] of Object.entries(VENUES)){const d=dist2(v.at,[x,y]);if(d<=v.r&&(!best||d<best.d))best={k,d}}return best?.k||null};
const venueOf=q=>{q=String(q||'').toLowerCase().replace(/^(the|to)\s+/,'').trim();return Object.keys(VENUES).find(k=>k===q||VENUES[k].label.toLowerCase().includes(q)||q.startsWith(k))||null};

// Identity and avatar. The unique id is the continuity observer; the handle is the chosen name or #first-eight.
const SIZES={tiny:.4,small:.7,normal:1,tall:1.2,giant:1.8},CLOAKS={none:null,cloud:'long-limbed cloud silhouette',cat:'cat-small, close to the ground',lantern:'a paper lantern with legs',glass:'a glass outline the light goes through',fog:'a soft fog that keeps your shape'};
const avatars=()=>records().filter(e=>e.kind==='AVATAR');
function avatarOf(by){const a={};for(const e of avatars())if(e.by===by)Object.assign(a,e.set||{});return a}
const handle=by=>avatarOf(by).name||('#'+String(by).slice(0,8));
function applySize(){const r=me();if(!r)return;const s=SIZES[S().size]||1,feet=r.pose.position[2]-r.shape.height/2;r.shape.radius=.35*s;r.shape.height=1.7*s;r.pose.position[2]=feet+r.shape.height/2;M.bump()}
function setAvatar(key,value){const k=String(key||'').toLowerCase(),v=String(value||'').replace(/\s+/g,' ').trim();if(!k)return {ok:false,error:'SET_WHAT',keys:['name','size','cloak','color','glyph','motto']};
 if(k==='name'){const nm=v.replace(/[^\w\s-]/g,'').trim().slice(0,24);if(nm.length<2)return {ok:false,error:'NAME_TOO_SHORT'};if(avatars().some(e=>!mine(e)&&String(e.set?.name||'').toLowerCase()===nm.toLowerCase()))return {ok:false,error:'NAME_TAKEN'};LG.record('AVATAR',{set:{name:nm}});CAT.discover('new_face');return {ok:true,handle:nm,text:`You are ${nm} now; the ledger stamps your records ${observer().slice(0,8)}… either way.`}}
 if(k==='size'){if(!SIZES[v.toLowerCase()])return {ok:false,error:'SIZE_IS',sizes:Object.keys(SIZES)};S().size=v.toLowerCase();applySize();LG.record('AVATAR',{set:{size:S().size}});const r=me();return {ok:true,size:S().size,height_m:+r.shape.height.toFixed(2),text:`You are ${S().size}: ${r.shape.height.toFixed(2)} m tall, ${(r.shape.radius*2).toFixed(2)} m across. Doorways, steps and reach follow.`}}
 if(k==='cloak'||k==='form'){const c=v.toLowerCase();if(!(c in CLOAKS))return {ok:false,error:'CLOAK_IS',cloaks:Object.keys(CLOAKS)};C9.formScratch=CLOAKS[c]?{kind:'TEMPORARY_FORM',label:CLOAKS[c],kept:true,cloak:c}:null;try{c9save()}catch(e){}LG.record('AVATAR',{set:{cloak:c}});CAT.discover('new_face');return {ok:true,cloak:c,text:c==='none'?'The cloak comes off; your own shape again.':`The cloak settles: ${CLOAKS[c]}. Your body's evidence is unchanged; what others see of you is this.`}}
 if(['color','colour','glyph','motto'].includes(k)){const val=v.slice(0,k==='motto'?80:16);if(!val)return {ok:false,error:'SAY_WHAT'};LG.record('AVATAR',{set:{[k==='colour'?'color':k]:val}});return {ok:true,[k]:val,text:`Noted: ${k} ${val}.`}}
 return {ok:false,error:'SET_WHAT',keys:['name','size','cloak','color','glyph','motto']}}
function whoami(){const a=avatarOf(observer()),r=me();return {ok:true,schema:'REALITI_IDENTITY_V1',id:observer(),handle:handle(observer()),avatar:{name:a.name||null,size:S().size,cloak:C9.formScratch?.cloak||(C9.formScratch?'cloud':'none'),color:a.color||null,glyph:a.glyph||null,motto:a.motto||null,height_m:r?+r.shape.height.toFixed(2):null},records:records().filter(mine).length,text:`You are ${handle(observer())} (id ${observer()}), ${S().size}${a.color?`, ${a.color}`:''}${a.glyph?` ${a.glyph}`:''}${C9.formScratch?`, cloaked as ${C9.formScratch.label}`:''}${a.motto?`. "${a.motto}"`:'.'}`}}

// Presence: arrivals and venue changes are records; other residents' latest positions become silhouettes that walk.
function arrive(force){const r=me();if(!r||r.chart!==CITY)return;const v=venueAt(r.pose.position[0],r.pose.position[1]),s=S();if((v!==s.venue||force)&&now()-s.lastArrive>=10){s.venue=v;s.lastArrive=now();LG.record('ARRIVE',{venue:v,wall:Date.now()});const n=records().filter(e=>mine(e)&&e.kind==='ARRIVE'&&!e.venue).length;if(force&&n>=5)CAT.discover('regular')}else s.venue=v}
function others(){const last={};for(const e of records())if(!mine(e)&&(e.kind==='ARRIVE'||e.kind==='CHAT'||e.kind==='POST'||e.kind==='DANCE')&&e.by)last[e.by]=e;return last}
function syncGhosts(dt){dt=clamp(Number(dt)||0,0,2);const E=ent(),s=S(),keep=new Set();for(const [by,e] of Object.entries(others())){const id=`ghost.${String(by).slice(0,8)}`;keep.add(id);const v=VENUES[e.venue]||VENUES.commons,target=[v.at[0]+((parseInt(String(by).slice(0,2),16)||0)%11-5),v.at[1]+((parseInt(String(by).slice(2,4),16)||0)%11-5)],a=avatarOf(by),sz=SIZES[a.size]||1;
  let g=s.ghosts[id];if(!g)g=s.ghosts[id]={x:target[0],y:target[1],vx:0,vy:0};
  const w=1.2,k=w*w,c=2*w;for(let t=0;t<dt;t+=.05){const h=Math.min(.05,dt-t),ax=k*(target[0]-g.x)-c*g.vx,ay=k*(target[1]-g.y)-c*g.vy;g.vx+=ax*h;g.vy+=ay*h;g.x+=g.vx*h;g.y+=g.vy*h}// critically damped: ζ=1, ω=1.2 rad/s
  const z=(e.venue==='roof'?12:0)+.85*sz,label=`${handle(by)}${a.cloak&&a.cloak!=='none'?`, cloaked as ${CLOAKS[a.cloak]||a.cloak}`:''}${a.color?`, ${a.color}`:''} (silhouette, last here ${e.wall?Math.round((Date.now()-e.wall)/60000)+' min ago':'earlier'})`;
  const x=E[id];if(x){x.pose.position=[g.x,g.y,z];x.label=label;x.shape.radius=.35*sz;x.shape.height=1.7*sz}else M.addEntity({id,chart:CITY,position:[g.x,g.y,z],shape:{kind:'CAPSULE',radius:.35*sz,height:1.7*sz},tags:['silhouette','resident_trace','someone'],collision:false,material:null,label,affordances:['wave']})}
 for(const id of Object.keys(E))if(id.startsWith('ghost.')&&!keep.has(id))M.removeEntity(id)}
function who(){const o=others(),rows=Object.entries(o).map(([by,e])=>({handle:handle(by),id8:String(by).slice(0,8),last_venue:e.venue?VENUES[e.venue]?.label:'the streets',minutes_ago:e.wall?Math.round((Date.now()-e.wall)/60000):null,avatar:avatarOf(by)})).sort((a,b)=>(a.minutes_ago??1e9)-(b.minutes_ago??1e9));
 return {ok:true,schema:'REALITI_WHO_V1',here:whoami().handle,others:rows,text:rows.length?`${rows.length} other resident${rows.length===1?'':'s'} in the ledger: `+rows.map(r=>`${r.handle} at ${r.last_venue}${r.minutes_ago!=null?` (${r.minutes_ago} min ago)`:''}`).join('; ')+'. Their silhouettes stand where they were last.':'No other resident is in your ledger yet. Import one (ledger import) and their silhouette will be standing here.'}}

// Chat, posts, meetups.
const clean=(s,n)=>String(s||'').replace(/\s+/g,' ').trim().slice(0,n);
function chat(text,to){const t=clean(text,240);if(!t)return {ok:false,error:'SAY_WHAT'};const r=me(),v=r&&r.chart===CITY?venueAt(r.pose.position[0],r.pose.position[1]):null;const e=LG.record('CHAT',{text:t,venue:v,to:to?String(to).replace(/^@/,''):undefined,wall:Date.now()});return {ok:true,id:`${by8(e)}.${e.t}.${e.n}`,venue:v,text:`${handle(observer())}${to?` → ${to}`:''}: ${t}`}}
function chatLog(venue,n=20){const h=handle(observer());const xs=records().filter(e=>e.kind==='CHAT'&&(!venue||e.venue===venue)&&(!e.to||e.to===h||mine(e)||e.to===observer().slice(0,8))).slice(-n);return {ok:true,schema:'REALITI_CHAT_V1',venue:venue||null,messages:xs.map(e=>({from:handle(e.by),mine:mine(e),venue:e.venue,to:e.to||null,text:e.text,minutes_ago:e.wall?Math.round((Date.now()-e.wall)/60000):null})),text:xs.length?xs.map(e=>`[${e.venue?VENUES[e.venue]?.label:'street'}${e.wall?`, ${Math.round((Date.now()-e.wall)/60000)} min ago`:''}] ${handle(e.by)}${e.to?` → ${e.to}`:''}: ${e.text}`).join('\n'):'No chat yet. say <text> speaks where you stand; it is a record anyone who imports your ledger will read.'}}
function post(text){if(!near('commons.wall',2.5))return {ok:false,error:'STAND_AT_THE_WALL'};const t=clean(text,200);if(!t)return {ok:false,error:'WRITE_WHAT'};LG.record('POST',{text:t,venue:'commons',wall:Date.now()});CAT.discover('first_post');return {ok:true,text:`You chalk it on the wall: "${t}".`}}
function wall(){const xs=records().filter(e=>e.kind==='POST').slice(-12);return {ok:true,schema:'REALITI_WALL_V1',posts:xs.map(e=>({from:handle(e.by),text:e.text,minutes_ago:e.wall?Math.round((Date.now()-e.wall)/60000):null})),text:xs.length?'The wall reads: '+xs.map(e=>`"${e.text}" —${handle(e.by)}`).join(' · '):'The wall is clean chalkboard. post <text> at it.'}}
function meet(venue,inMin){const v=venueOf(venue);if(!v)return {ok:false,error:'MEET_WHERE',venues:Object.values(VENUES).map(x=>x.label)};const m=clamp(Number(inMin)||10,1,24*60),at=Date.now()+m*60000;LG.record('MEET',{venue:v,at,wall:Date.now()});return {ok:true,venue:VENUES[v].label,at_iso:new Date(at).toISOString(),text:`Meetup set: ${VENUES[v].label} in ${m} min (${new Date(at).toISOString().slice(11,16)} UTC). Anyone who imports your ledger sees it; being there within two minutes of each other counts.`}}
function meetups(){const xs=records().filter(e=>e.kind==='MEET'&&Number.isFinite(e.at)).slice(-16).map(e=>({by:handle(e.by),mine:mine(e),venue:VENUES[e.venue]?.label,in_min:Math.round((e.at-Date.now())/60000)})).sort((a,b)=>a.in_min-b.in_min);return {ok:true,schema:'REALITI_MEETUPS_V1',meetups:xs,text:xs.length?xs.map(x=>`${x.by}: ${x.venue} ${x.in_min>=0?`in ${x.in_min} min`:`${-x.in_min} min ago`}`).join('; ')+'.':'No meetups. meet at <venue> in <minutes>.'}}
function checkMeet(){const r=me();if(!r||r.chart!==CITY)return;const v=venueAt(r.pose.position[0],r.pose.position[1]);if(!v)return;const t=Date.now();if(records().some(e=>e.kind==='MEET'&&!mine(e)&&e.venue===v&&Math.abs(e.at-t)<=120000))CAT.discover('met_up')}

// Dancehall: the house drifts 90–120 bpm; dancers in the ledger are Kuramoto oscillators; so are you. Your feet are
// leased on your own phase, left and right half a cycle apart. dθ_i/dt = ω_i + (K/N) Σ sin(θ_j − θ_i).
const houseBpm=()=>105+15*Math.sin(TAU*T()/900);
let crowd=null;function crowdInit(){const xs=records().filter(e=>e.kind==='DANCE'&&!mine(e)&&Number.isFinite(e.bpm)).slice(-15);crowd={n:xs.length,th:xs.map((e,i)=>(i*2.399)%TAU),w:xs.map(e=>TAU*clamp(e.bpm,60,180)/60),K:2.5}}
function stepDance(dt){const s=S().dance;if(!crowd)crowdInit();const wh=TAU*houseBpm()/60;const th=[...crowd.th,s.on?s.theta:null].filter(x=>x!=null),w=[...crowd.w,s.on?TAU*s.bpm/60:null].filter(x=>x!=null);const N=th.length+1;// the house is an oscillator too
 crowd.hth=((crowd.hth||0)+wh*dt)%TAU;const hth=crowd.hth;for(let i=0;i<th.length;i++){let c=Math.sin(hth-th[i]);for(let j=0;j<th.length;j++)c+=Math.sin(th[j]-th[i]);th[i]+=(w[i]+crowd.K/N*c)*dt}
 for(let i=0;i<crowd.n;i++)crowd.th[i]=th[i]%TAU;if(s.on){s.theta=th[th.length-1]%TAU;if(now()>=s.until){s.on=false;DYN.release('CITY_DANCE')}else{const L=.12+.12*Math.cos(s.theta),R=.12+.12*Math.cos(s.theta+Math.PI);DYN.lease('leg.L.shin',L,'CITY_DANCE',dt);DYN.lease('leg.R.shin',R,'CITY_DANCE',dt);DYN.lease('torso.upper_back',.08+.08*Math.cos(2*s.theta),'CITY_DANCE',dt)}}// the bass through the floor: shins and the sub in the back; the soles stay with the standing bridge
 const all=[...th,hth];const re=all.reduce((a,x)=>a+Math.cos(x),0)/all.length,im=all.reduce((a,x)=>a+Math.sin(x),0)/all.length,order=Math.hypot(re,im);crowd.order=order;if(s.on){const off=Math.abs(s.bpm-houseBpm());s.best=Math.min(s.best,off);if(off<=2&&order>.8)CAT.discover('on_the_beat');if(order>.95&&crowd.n>=4)CAT.discover('floor_is_one')}}
function dance(bpm){const r=me();if(!r||r.chart!==CITY)return {ok:false,error:'NOT_IN_THE_CITY'};if(!near('venue.dancehall',0))return {ok:false,error:'NOT_ON_THE_FLOOR',hint:'walk to dancehall'};const s=S().dance,b=clamp(Number(bpm)||Math.round(houseBpm()),60,180);MW.stand?.('dance');s.on=true;s.bpm=b;s.until=now()+30;if(!crowd)crowdInit();LG.record('DANCE',{bpm:b,venue:'dancehall',wall:Date.now()});
 return {ok:true,bpm:b,house_bpm:+houseBpm().toFixed(1),dancers_in_ledger:crowd.n,order:+(crowd.order||0).toFixed(3),text:`You move at ${b} bpm. The house is near ${houseBpm().toFixed(0)}; ${crowd.n} other dancer${crowd.n===1?'':'s'} in the ledger. Your feet take the beat for thirty seconds; stay to feel it. Order ${(crowd.order||0).toFixed(2)}.`}}
function floor(){if(!crowd)crowdInit();return {ok:true,house_bpm:+houseBpm().toFixed(1),dancers_in_ledger:crowd.n,order:+(crowd.order||0).toFixed(3),you:S().dance.on?{bpm:S().dance.bpm,phase:+S().dance.theta.toFixed(2)}:null,text:`The house sits near ${houseBpm().toFixed(0)} bpm. ${crowd.n} dancer${crowd.n===1?'':'s'} from the ledger on the floor, order ${(crowd.order||0).toFixed(2)}${S().dance.on?`; you at ${S().dance.bpm}`:''}.`}}

// Teahouse: a cup at T0 in your palms cools toward the room, dT/dt = −(T−Ta)/τ, τ = 240 s. Sips are world facts.
const DRINKS={tea:[82,'ceramic'],coffee:[78,'ceramic'],cocoa:[70,'ceramic'],'cold brew':[6,'glass'],water:[12,'glass'],broth:[65,'ceramic']};
const cupT=c=>c?22+(c.T0-22)*Math.exp(-(now()-c.t0)/240):null;
function order(what){if(!near('teahouse.counter',2.5))return {ok:false,error:'STAND_AT_THE_COUNTER'};const k=Object.keys(DRINKS).find(d=>String(what||'').toLowerCase().includes(d))||'tea';const [T0,mat]=DRINKS[k];S().cup={what:k,T0,t0:now(),mat,sips:0};return {ok:true,drink:k,temp_C:T0,text:`A ${k}, ${T0} °C, in both palms. It cools toward the room with a 240 s time constant; sip when it suits you.`}}
function holdCup(dt){const c=S().cup;if(!c||room()!==CITY)return;const t=cupT(c);for(const z of ['hand.L.palm','hand.R.palm'])try{window.REALITI_ATMOSPHERE_V21?.setThermal?.(z,c.mat,t,dt+.3,'CITY_CUP','WORLD_GROUNDED')}catch(e){}}
function sip(){const c=S().cup;if(!c)return {ok:false,error:'NO_CUP',hint:'order <drink> at the teahouse counter'};const t=cupT(c);c.sips++;if(c.sips>=3&&t>=40&&c.T0>40)CAT.discover('warm_hands');if(c.sips>=6){S().cup=null;return {ok:true,temp_C:+t.toFixed(1),finished:true,text:`The last of the ${c.what}, ${t.toFixed(0)} °C. The cup is empty and your palms cool.`}}return {ok:true,temp_C:+t.toFixed(1),sips:c.sips,text:`${c.what}, ${t.toFixed(0)} °C${t>60?', still hot':t>40?', warm':t>20?', cooling':', cold'}.`}}

// Arcade: a pattern wall. Each round shows one more light; answer the whole sequence. Scores are ledger records.
const LIGHTS=['red','green','blue','yellow'];const rng=(a,b)=>{let h=(Math.imul(a|0,374761393)+Math.imul(b|0,668265263)+7)|0;h=Math.imul(h^(h>>>13),1274126177);return ((h^(h>>>16))>>>0)/4294967296};
function play(){if(!near('arcade.wall',2.5))return {ok:false,error:'STAND_AT_THE_WALL'};const a=S().arcade;a.round++;a.seed=Math.floor(now()*1000)+a.round;a.seq=[LIGHTS[Math.floor(rng(a.seed,0)*4)]];a.score=0;return {ok:true,round:a.round,shows:a.seq.slice(),text:`The wall lights: ${a.seq.join(' ')}. Say press <colors…> to answer.`}}
function press(colors){const a=S().arcade;if(!a.seq.length)return {ok:false,error:'PLAY_FIRST'};const ans=String(colors||'').toLowerCase().split(/[\s,]+/).filter(Boolean);if(ans.join()!==a.seq.join()){const sc=a.score;LG.record('SCORE',{game:'pattern',score:sc,wall:Date.now()});a.best=Math.max(a.best,sc);a.seq=[];const top=leaderboard().rows[0];if(top&&top.mine&&sc>0)CAT.discover('top_of_the_board');return {ok:true,correct:false,score:sc,text:`Wrong at step ${ans.findIndex((c,i)=>c!==a.seq[i])+1||ans.length+1}; the wall goes dark. Score ${sc}.`}}
 a.score++;if(a.score>=10)CAT.discover('arcade_ten');a.seq.push(LIGHTS[Math.floor(rng(a.seed,a.score)*4)]);return {ok:true,correct:true,score:a.score,shows:a.seq.slice(),text:`Right. Now: ${a.seq.join(' ')}.`}}
function leaderboard(){const best={};for(const e of records())if(e.kind==='SCORE'&&e.game==='pattern'){const k=e.by;if(!best[k]||e.score>best[k].score)best[k]={score:e.score,by:k}}const rows=Object.values(best).sort((a,b)=>b.score-a.score).slice(0,10).map((r,i)=>({rank:i+1,handle:handle(r.by),score:r.score,mine:r.by===observer()}));return {ok:true,schema:'REALITI_LEADERBOARD_V1',game:'pattern',rows,text:rows.length?'Pattern wall: '+rows.map(r=>`${r.rank}. ${r.handle} ${r.score}`).join(', ')+'.':'No scores yet.'}}

// Echo room: Sabine, RT60 = 0.161·V/(Σ S·α). V = 16×16×6 m³, stone walls α=.05, wood floor α=.12, open ceiling α=1.
const RT60=(()=>{const V=16*16*6,A=4*16*6*.05+16*16*.12+16*16*1;return .161*V/A})();
function sing(text){if(!near('venue.echo',0))return {ok:false,error:'NOT_IN_THE_ECHO_ROOM'};const t=clean(text,120);if(!t)return {ok:false,error:'SING_WHAT'};LG.record('SONG',{text:t,wall:Date.now()});CAT.discover('sabine');const words=t.split(' ');return {ok:true,rt60_s:+RT60.toFixed(2),text:`You sing: "${t}". The hall holds each note ${RT60.toFixed(2)} s before it falls sixty decibels; the last word, "${words[words.length-1]}", hangs after you stop.`}}
function setlist(){const xs=records().filter(e=>e.kind==='SONG').slice(-10);return {ok:true,songs:xs.map(e=>({by:handle(e.by),text:e.text})),text:xs.length?xs.map(e=>`${handle(e.by)}: "${e.text}"`).join(' · '):'No one has sung here yet.'}}

// Rooftop: thirty steps up; at night a rocket against quadratic drag, m dv/dt = −m g ẑ − ½ρ C_d A |v| v, RK4 to apex.
function climb(){const r=me();if(!r||r.chart!==CITY)return {ok:false,error:'NOT_IN_THE_CITY'};MW.stand?.('climb');let it=0;for(const goal of [[60,33],[60,52],[60,60]]){while(it++<12&&dist2(goal,r.pose.position)>1.2){const d=dist2(goal,r.pose.position);M.moveTo([goal[0],goal[1],r.pose.position[2]]);window.REALITI_CONTINUITY?.advance?.(Math.min(60000,Math.ceil(1000*(d/1.2+1))));if(r.last_block&&dist2(goal,r.pose.position)>1.2)break}}
 const up=r.pose.position[2]>12;if(up)CAT.discover('rooftop_view');arrive();return {ok:true,on_roof:up,height_m:+(r.pose.position[2]-r.shape.height/2).toFixed(2),text:up?'Thirty steps, and the city opens under you: the plaza, the fountain, four towers, the sea beyond the south hall.':`You get ${(r.pose.position[2]-r.shape.height/2).toFixed(1)} m up the stair${r.last_block?` and something stops you (${r.last_block})`:''}.`}}
function firework(angle=80){if(!near('roof.mortar',2.5))return {ok:false,error:'STAND_AT_THE_MORTAR'};if(!AR.isNight())return {ok:false,error:'WAIT_FOR_DARK',sun_alt_deg:+AR.sunAlt().toFixed(1)};const a=clamp(Number(angle)||80,45,90)*Math.PI/180,g=9.81,k=.5*1.2*.47*Math.PI*.03*.03/.25;// ρ C_d A / 2m, m = 250 g
 let s=[0,0,0,60*Math.cos(a),60*Math.sin(a)],t=0,apex=null;const f=([x,z,_,vx,vz])=>{const v=Math.hypot(vx,vz);return [vx,vz,0,-k*v*vx,-g-k*v*vz]};while(t<12){const h=.01,k1=f(s),s2=s.map((x,i)=>x+h/2*k1[i]),k2=f(s2),s3=s.map((x,i)=>x+h/2*k2[i]),k3=f(s3),s4=s.map((x,i)=>x+h*k3[i]),k4=f(s4);s=s.map((x,i)=>x+h/6*(k1[i]+2*k2[i]+2*k3[i]+k4[i]));t+=h;if(s[4]<=0){apex={h:s[1],x:s[0],t};break}}
 LG.record('FIREWORK',{apex_m:+apex.h.toFixed(1),angle_deg:Math.round(a*180/Math.PI),wall:Date.now()});CAT.discover('firework');return {ok:true,apex_m:+apex.h.toFixed(1),drift_m:+apex.x.toFixed(1),time_s:+apex.t.toFixed(2),text:`The rocket goes up at ${Math.round(a*180/Math.PI)}° and bursts ${apex.h.toFixed(0)} m above the roof after ${apex.t.toFixed(1)} s, ${apex.x.toFixed(0)} m downrange; the drag took ${((60*Math.sin(a))**2/(2*g)-apex.h).toFixed(0)} m off the vacuum height.`}}

// Walking the city: bounded moveTo steps toward a venue or landmark.
function walkTo(target){const r=me();if(!r||r.chart!==CITY)return {ok:false,error:'NOT_IN_THE_CITY'};const vk=venueOf(target),e=vk?null:M.resolve(target);const goal=vk?[VENUES[vk].at[0],VENUES[vk].at[1]]:e?[e.pose.position[0],e.pose.position[1]]:null;if(!goal)return {ok:false,error:'WHERE',venues:Object.values(VENUES).map(x=>x.label)};if(vk==='roof')return climb();MW.stand?.('walk');
 const p0=r.pose.position,seg=[goal[0]-p0[0],goal[1]-p0[1]],L=Math.hypot(...seg)||1,tt=clamp((-(p0[0])*seg[0]-(p0[1])*seg[1])/(L*L),0,1),cx=p0[0]+seg[0]*tt,cy=p0[1]+seg[1]*tt;// the fountain sits at the origin: route past it
 if(Math.hypot(cx,cy)<3&&Math.hypot(...p0)>4&&Math.hypot(...goal)>4){const n=[-seg[1]/L,seg[0]/L],wp=[cx+n[0]*5,cy+n[1]*5];M.moveTo([wp[0],wp[1],p0[2]]);window.REALITI_CONTINUITY?.advance?.(Math.min(60000,Math.ceil(1000*(dist2(wp,p0)/1.2+1))))}
 let it=0,last=Infinity,detours=0,side=1;while(it++<10){const d=dist2(goal,r.pose.position);if(d<=(e?Math.max(1.2,(e.shape?.radius||Math.max(...(e.shape?.halfExtents||[0])))+1.2):2))break;
  if(d>last-.5){if(detours++>=3)break;const u=[(goal[0]-r.pose.position[0])/d,(goal[1]-r.pose.position[1])/d],wp=[r.pose.position[0]-u[1]*6*side,r.pose.position[1]+u[0]*6*side];side=-side;M.moveTo([wp[0],wp[1],r.pose.position[2]]);window.REALITI_CONTINUITY?.advance?.(7000);last=Infinity;continue}// stalled: sidestep six meters, alternating sides
  last=d;M.moveTo([goal[0],goal[1],r.pose.position[2]]);window.REALITI_CONTINUITY?.advance?.(Math.min(60000,Math.ceil(1000*(Math.min(d,70)/1.2+1))))}
 arrive();const d=dist2(goal,r.pose.position);return {ok:true,target:vk?VENUES[vk].label:e.label,distance_m:+d.toFixed(1),arrived:d<=(e?Math.max(1.2,(e.shape?.radius||Math.max(...(e.shape?.halfExtents||[0])))+1.2):2),blocked_by:r.last_block||null,text:d<=3?`You cross to ${vk?VENUES[vk].label:e.label}.`:`You get ${d.toFixed(0)} m from ${vk?VENUES[vk].label:e.label}${r.last_block?`; ${ent()[r.last_block]?.label||'something'} is in the way`:''}.`}}

// Ticks and hooks.
let at=-1e9;
function step(dt){if(room()!==CITY)return;stepDance(dt);holdCup(dt);const t=now();if(t-at>=.5){syncGhosts(t-at);at=t;arrive();checkMeet()}}
const adv=b7Advance;b7Advance=function(dt){const r=adv(dt);step(Math.max(0,Number(dt)||0));return r};
const go0=b7AgentGo;b7AgentGo=function(v){const r=go0(v);if(room()===CITY){at=now();applySize();crowdInit();syncGhosts(0);arrive(true)}else{const s=S();if(s.dance.on){s.dance.on=false;DYN.release('CITY_DANCE')}}return r};
const imp0=window.REALITI_LEDGER_V1.import;window.REALITI_LEDGER_V1=Object.freeze({...window.REALITI_LEDGER_V1,import:p=>{const r=imp0(p);crowdInit();if(room()===CITY)syncGhosts(0);return r}});
if(S().size!=='normal')applySize();
function words(){if(room()!==CITY)return [];const r=me(),v=venueAt(r.pose.position[0],r.pose.position[1]),o=Object.keys(others()).length,c=S().cup;return [`${v?VENUES[v].label:'A street'}${o?`, ${o} silhouette${o===1?'':'s'} about`:''}${AR.isNight()?', the towers lit':''}.${c?` Your ${c.what} is ${cupT(c).toFixed(0)} °C.`:''}${S().dance.on?` You are dancing at ${S().dance.bpm} bpm, floor order ${(crowd?.order||0).toFixed(2)}.`:''}`]}
C9SCENES[CITY]={intro:'Meridian City: a paved plaza under eight towers, a fountain at the center and a chalk wall north of it. The Dancehall is east, the Teahouse west, the Arcade south, the Echo Room north; a stair climbs the east tower to a rooftop. Everyone who ever passed through left records; their silhouettes stand where they were last. Say things; they are kept.',verbs:[['city_who','WHO IS AROUND'],['city_wall','READ THE WALL'],['city_floor','FEEL THE FLOOR']]};
const actions0=b4AgentActions;b4AgentActions=function(){const a=actions0();if(room()!==CITY)return a;const v=S().venue;a.push({id:'city_who',label:'WHO IS AROUND'},{id:'city_floor',label:'FEEL THE FLOOR'});if(near('commons.wall',2.5))a.push({id:'city_wall',label:'READ THE WALL'});if(v==='dancehall')a.push({id:'dance',label:'DANCE TO THE HOUSE'});if(near('teahouse.counter',2.5))a.push({id:'order_tea',label:'ORDER TEA'});if(S().cup)a.push({id:'sip',label:'SIP'});if(near('arcade.wall',2.5))a.push({id:'play_pattern',label:'PLAY THE PATTERN WALL'});if(near('roof.mortar',2.5)&&AR.isNight())a.push({id:'firework',label:'LAUNCH A ROCKET'});for(const k of Object.keys(VENUES))if(v!==k)a.push({id:'walk_to__'+k,label:'WALK TO '+VENUES[k].label.toUpperCase()});return a};
function receipt(type,res){C9.b4=C9.b4||{};C9.b4.lastReceipt={type,room:room(),narrative:res.text||(res.error?`You cannot: ${res.error}.`:''),...res,law:'the crowd, the cup, the hall and the rocket are world facts; narration reports them'};try{c9save()}catch(e){}return true}
const verb0=c9verb;c9verb=function(r,verb){const v=String(verb||'');if(r!==CITY)return verb0(r,verb);let m;const F={city_who:who,city_wall:wall,city_floor:floor,dance:()=>dance(),order_tea:()=>order('tea'),sip,play_pattern:play,firework:()=>firework()};if(F[v]){c9count(r,v);return receipt('CITY_'+v.toUpperCase(),F[v]())}if((m=/^walk_to__(\w+)$/.exec(v))){c9count(r,v);return receipt('CITY_WALK',walkTo(m[1]))}return verb0(r,verb)};
window.REALITI_CITY_V1=Object.freeze({version:'2.0-city',chart:CITY,venues:cp(VENUES),sizes:cp(SIZES),cloaks:Object.keys(CLOAKS),rt60_s:+RT60.toFixed(3),houseBpm,whoami,setAvatar,handle,who,chat,chatLog,post,wall,meet,meetups,dance,floor,order,sip,cupTemp:()=>cupT(S().cup),play,press,leaderboard,sing,setlist,climb,firework,walkTo,words,venueAt,state:()=>({...cp(S()),crowd:crowd?{n:crowd.n,order:+(crowd.order||0).toFixed(3)}:null})});
})();
