(()=>{
'use strict';
// Catnip, second pack. Fishing: bites are a seeded next-reaction process whose rate follows the tide, the hour and the
// place, so the fish are real statistics rather than dice; catches are CATCH records and a leaderboard. The harbor race:
// a timed course round three marks by boat, with RACE records and the best times across every ledger you carry. Letters:
// LETTER records addressed to a handle, readable by that handle's resident once the records reach them.
const M=window.REALITI_MATRIX_V1,AR=window.REALITI_ARCHIPELAGO_V1,LG=window.REALITI_LEDGER_V1,CAT=window.REALITI_CATNIP_V1,LGM=window.REALITI_LONG_GAME_V1,CT=window.REALITI_CITY_V1,TL=window.REALITI_TIMELINE_V1;if(!M||!AR||!LG||!CAT||!LGM||!CT||!TL)return;
const ISLE=AR.chart,now=()=>Number(C9?.b7?.clock||0),room=()=>C9?.currentRoom,cp=x=>JSON.parse(JSON.stringify(x)),T=LGM.T;
const me=()=>M.state().residents['resident:self'],ent=()=>M.entities(),observer=()=>String(C9?.verticalContinuity?.observer||'local'),records=()=>(C9.ledger?.records||[]),mine=e=>e.by===observer(),handle=by=>CT.handle(by);
function S(){const w=(C9.chapter2=C9.chapter2||{v:1});w.pack2=w.pack2||{fishing:null,casts:0,race:null,races:0};return w.pack2}
for(const [id,text] of Object.entries({first_fish:'A bite, a weight, a fish in the boat.',big_fish:'A fish over three kilos: the tide and the hour were right.',patient_angler:'Ten casts; the sea does not hurry for anyone.',race_finished:'Round the marks and home: the harbor race, timed to the tenth of a second.',race_record:'The fastest time round the course in every ledger you carry.',letter_sent:'A letter sealed for another resident, carried by the ledger.',letter_received:'A letter addressed to you, opened in your hands.'}))CAT.register(id,text);

// Fishing. Rate per second = base(place) · tide factor · hour factor; bites from a next-reaction channel; the catch is
// drawn from a seeded generator keyed by the bite. Cast once, stay, reel when it bites (a bite waits twelve seconds).
const SPOTS={dock:{base:1/45,near:'harbor.dock',label:'off the dock'},boat:{base:1/30,label:'from the boat'},stones:{base:1/60,near:'stones.east',label:'below the east stone'}};
const FISH=[['bream',.4,1.6],['mackerel',.3,1.2],['pollock',.8,3.2],['bass',1,4.5],['eel',.5,2]];
const tideFactor=()=>{const t=LGM.tide();return .5+(t.rising?1:.4)+.4*Math.abs(t.height_m)};
const hourFactor=()=>{const a=AR.sunAlt();return a<0?.7:a<15?1.6:a<45?1:.6};
const ratePerSec=spot=>SPOTS[spot].base*tideFactor()*hourFactor();
function spotHere(){const r=me();if(!r||r.chart!==ISLE)return null;if(AR.state().boat.aboard)return 'boat';for(const [k,s] of Object.entries(SPOTS)){if(!s.near)continue;const e=ent()[s.near];if(e&&Math.max(0,M.sdf(e,r.pose.position))<=2)return k}return null}
let chan=null;
function cast(){const spot=spotHere();if(!spot)return {ok:false,error:'NOWHERE_TO_FISH',hint:'the dock, the boat, or below the east stone'};const s=S();if(s.fishing)return {ok:true,already:true,text:'Your line is already out. Stay, and reel when it bites.'};s.casts++;const seed=(Math.floor(T()*1000)^0x5eed)>>>0;s.fishing={spot,t0:now(),seed,bite:null,hooked:null,missed:0};chan=TL.channel(seed);if(s.casts>=10)CAT.discover('patient_angler');const rpm=60*ratePerSec(spot);return {ok:true,spot:SPOTS[spot].label,rate_per_min:+rpm.toFixed(2),text:`You cast ${SPOTS[spot].label}. Stay; the sea bites about ${rpm.toFixed(1)} times a minute here, now.`}}
function stepFishing(){const s=S().fishing;if(!s)return;if(!chan)chan=TL.channel(s.seed);const fired=chan.step(now(),ratePerSec(s.spot));if(fired.length&&!s.bite){s.bite=now();const r=TL.rng((s.seed^Math.floor(s.bite*10))>>>0);const u=r();if(u<.02)s.hooked={name:'boot',kg:0};else{const pick=FISH[Math.floor(r()*FISH.length)];s.hooked={name:pick[0],kg:+(pick[1]+(pick[2]-pick[1])*Math.pow(r(),2)).toFixed(2)}}}
 if(s.bite&&now()-s.bite>12){s.bite=null;s.hooked=null;s.missed++}}
function reel(){const s=S().fishing;if(!s)return {ok:false,error:'NO_LINE_OUT'};S().fishing=null;chan=null;if(!s.bite)return {ok:true,caught:null,missed:s.missed,text:`You reel in. Weed and a cold line${s.missed?`; ${s.missed} bite${s.missed===1?'':'s'} came and went`:''}.`};const f=s.hooked,wait=+(s.bite-s.t0).toFixed(1);
 LG.record('CATCH',{fish:f.name,kg:f.kg,spot:s.spot,wait_s:wait,wall:Date.now()});if(f.name==='boot')return {ok:true,caught:'boot',kg:0,wait_s:wait,text:`Weight on the line, and up comes a boot. ${wait} s for a boot.`};CAT.discover('first_fish');if(f.kg>=3)CAT.discover('big_fish');return {ok:true,caught:f.name,kg:f.kg,wait_s:wait,text:`A ${f.name}, ${f.kg} kg, after ${wait} s. It goes in the bucket.`}}
function fishboard(){const best={};for(const e of records())if(e.kind==='CATCH'&&e.kg>0&&(!best[e.by]||e.kg>best[e.by].kg))best[e.by]=e;const rows=Object.values(best).sort((a,b)=>b.kg-a.kg).slice(0,10).map((e,i)=>({rank:i+1,handle:handle(e.by),fish:e.fish,kg:e.kg,mine:mine(e)}));return {ok:true,schema:'REALITI_FISHBOARD_V1',rows,text:rows.length?'Biggest fish: '+rows.map(r=>`${r.rank}. ${r.handle} ${r.fish} ${r.kg} kg`).join(', ')+'.':'No fish landed yet.'}}
function fishing(){const s=S().fishing;if(!s)return {ok:true,line_out:false,text:'No line out.'};return {ok:true,line_out:true,spot:SPOTS[s.spot].label,since_s:+(now()-s.t0).toFixed(1),bite:!!s.bite,rate_per_min:+(60*ratePerSec(s.spot)).toFixed(2),text:s.bite?'Something has the line. Reel.':`Line out ${SPOTS[s.spot].label} for ${(now()-s.t0).toFixed(0)} s. Nothing yet.`}}

// The harbor race: from the dock round three marks and back, by boat, timed in world seconds.
const deep=([x,y])=>{let k=0;while(AR.h(x,y)>-2.5&&k++<60)y-=6;return [+x.toFixed(1),+y.toFixed(1)]};// marks sit in water at least 2.5 m deep; open sea lies south of the harbor
const MARKS=[[120,AR.shore_y-60],[0,AR.shore_y-204],[42,AR.shore_y-48]].map(deep);
MARKS.forEach((m,i)=>M.addEntity({id:`race.mark_${i+1}`,chart:ISLE,position:[m[0],m[1],.6],shape:{kind:'SPHERE',radius:.5},tags:['buoy','mark','race'],collision:false,material:'ceramic',label:`race mark ${i+1}`,affordances:[]}));
function race(){const b=AR.state().boat;if(!b.aboard)return {ok:false,error:'BOARD_THE_BOAT_FIRST'};const s=S();if(s.race)return {ok:false,error:'RACE_UNDER_WAY',next:s.race.next+1};s.race={t0:now(),next:0,log:[]};return {ok:true,marks:MARKS.map((m,i)=>({mark:i+1,at:m})),text:`Go. Round mark 1 (${MARKS[0].map(x=>x.toFixed(0)).join(', ')}), mark 2, mark 3, then back to the dock. The clock is running.`}}
function stepRace(){const s=S().race;if(!s)return;const b=AR.state().boat;if(s.next<MARKS.length){const m=MARKS[s.next];if(Math.hypot(b.x-m[0],b.y-m[1])<15){s.log.push({mark:s.next+1,t:+(now()-s.t0).toFixed(1)});s.next++}}
 else{const dock=ent()['harbor.dock'].pose.position;if(Math.hypot(b.x-dock[0],b.y-dock[1])<20){const time=+(now()-s.t0).toFixed(1);LG.record('RACE',{time_s:time,marks:s.log,wall:Date.now()});S().race=null;S().races++;S().lastRace={time_s:time,marks:s.log};CAT.discover('race_finished');const best=raceboard().rows[0];if(best&&best.mine&&best.time_s===time)CAT.discover('race_record')}}}
function raceboard(){const best={};for(const e of records())if(e.kind==='RACE'&&Number.isFinite(e.time_s)&&(!best[e.by]||e.time_s<best[e.by].time_s))best[e.by]=e;const rows=Object.values(best).sort((a,b)=>a.time_s-b.time_s).slice(0,10).map((e,i)=>({rank:i+1,handle:handle(e.by),time_s:e.time_s,mine:mine(e)}));return {ok:true,schema:'REALITI_RACEBOARD_V1',rows,text:rows.length?'Harbor race: '+rows.map(r=>`${r.rank}. ${r.handle} ${r.time_s} s`).join(', ')+'.':'No one has raced yet.'}}
function raceState(){const s=S().race;if(!s)return {ok:true,racing:false,last:S().lastRace||null,text:S().lastRace?`Last race ${S().lastRace.time_s} s.`:'Not racing. race starts the clock from the boat.'};const b=AR.state().boat,m=s.next<MARKS.length?MARKS[s.next]:ent()['harbor.dock'].pose.position;return {ok:true,racing:true,elapsed_s:+(now()-s.t0).toFixed(1),next:s.next<MARKS.length?`mark ${s.next+1}`:'the dock',distance_m:+Math.hypot(b.x-m[0],b.y-m[1]).toFixed(0),text:`${(now()-s.t0).toFixed(0)} s. Next: ${s.next<MARKS.length?`mark ${s.next+1}`:'the dock'}, ${Math.hypot(b.x-m[0],b.y-m[1]).toFixed(0)} m.`}}

// Letters: to a handle; readable by that handle's resident (by name or by id prefix) once the record reaches them.
function send(to,text){const t=String(text||'').replace(/\s+/g,' ').trim().slice(0,400);const h=String(to||'').replace(/^@/,'').trim();if(!h)return {ok:false,error:'TO_WHOM'};if(!t)return {ok:false,error:'WRITE_SOMETHING'};LG.record('LETTER',{to:h,text:t,wall:Date.now()});CAT.discover('letter_sent');return {ok:true,to:h,text:`Sealed for ${h}. It travels with your ledger; ${h} reads it when your records reach them.`}}
const forMe=e=>{const h=String(e.to||'').toLowerCase(),my=handle(observer()).toLowerCase(),id=observer().toLowerCase();return h===my||h===my.replace(/^#/,'')||('#'+id.slice(0,8))===h||(h.length>=6&&id.startsWith(h))};
function mail(){const inbox=records().filter(e=>e.kind==='LETTER'&&!mine(e)&&forMe(e)),sent=records().filter(e=>e.kind==='LETTER'&&mine(e));if(inbox.length)CAT.discover('letter_received');return {ok:true,schema:'REALITI_MAIL_V1',inbox:inbox.map(e=>({from:handle(e.by),text:e.text,minutes_ago:e.wall?Math.round((Date.now()-e.wall)/60000):null})),sent:sent.map(e=>({to:e.to,text:e.text})),text:inbox.length?inbox.map(e=>`From ${handle(e.by)}: "${e.text}"`).join(' · '):`No letters for ${handle(observer())}.${sent.length?` ${sent.length} sent.`:''}`}}

let at=-1e9;const adv=b7Advance;b7Advance=function(dt){const r=adv(dt);if(room()===ISLE){const t=now();if(t-at>=.25){at=t;stepFishing();stepRace()}}return r};
const actions0=b4AgentActions;b4AgentActions=function(){const a=actions0();if(room()!==ISLE)return a;const sp=spotHere();if(sp&&!S().fishing)a.push({id:'cast',label:'CAST A LINE'});if(S().fishing)a.push({id:'reel',label:'REEL IN'});if(AR.state().boat.aboard&&!S().race)a.push({id:'race',label:'START THE HARBOR RACE'});return a};
function receipt(type,res){C9.b4=C9.b4||{};C9.b4.lastReceipt={type,room:room(),narrative:res.text||(res.error?`You cannot: ${res.error}.`:''),...res,law:'bites, marks and letters are records and processes; narration reports them'};try{c9save()}catch(e){}return true}
const verb0=c9verb;c9verb=function(r,verb){const v=String(verb||'');if(r!==ISLE)return verb0(r,verb);const F={cast,reel,race};if(F[v]){c9count(r,v);return receipt('ISLAND_'+v.toUpperCase(),F[v]())}return verb0(r,verb)};
window.REALITI_CATNIP_PACK2_V1=Object.freeze({version:'1.0',cast,reel,fishing,fishboard,race,raceState,raceboard,marks:()=>cp(MARKS),send,mail,rate:()=>({tide:+tideFactor().toFixed(2),hour:+hourFactor().toFixed(2)}),state:()=>cp(S())});
})();
