(()=>{
'use strict';
// Secrets, wonder and catnip, third pass. A sea cave that only the low tide opens, lit by plankton that answer motion.
// The islands share the Star Deck's sky: constellations by name, the comet when it is up, meteors as a seeded process
// that showers every third island day, and stars you may name for everyone who carries your ledger. A rain forecast
// from the band's own motion, scored when the rain arrives. The keeper's riddles, answered with measurements from five
// rooms, pay out a lantern that gives the Undercity three meters of sight. Dreams composed from your own records. A hot
// spring. Words scratched into the dark for the next hand to read.
const M=window.REALITI_MATRIX_V1,AR=window.REALITI_ARCHIPELAGO_V1,LG=window.REALITI_LEDGER_V1,CAT=window.REALITI_CATNIP_V1,LGM=window.REALITI_LONG_GAME_V1,CT=window.REALITI_CITY_V1,TL=window.REALITI_TIMELINE_V1,SN=window.REALITI_SENSES_V1,U=window.REALITI_UNDERCITY_V1,ATM=window.REALITI_ATMOSPHERE_V21;if(!M||!AR||!LG||!CAT||!LGM||!CT||!TL||!SN||!U||!ATM)return;
const ISLE=AR.chart,CITY=CT.chart,NEST='CLOUD_NINE_NEST',UNDER=U.chart,now=()=>Number(C9?.b7?.clock||0),room=()=>C9?.currentRoom,cp=x=>JSON.parse(JSON.stringify(x)),T=LGM.T,TAU=2*Math.PI;
const me=()=>M.state().residents['resident:self'],ent=()=>M.entities(),observer=()=>String(C9?.verticalContinuity?.observer||'local'),records=()=>(C9.ledger?.records||[]),mine=e=>e.by===observer(),handle=by=>CT.handle(by);
const inside=(id,r=me())=>{const e=ent()[id];return !!(e&&r&&r.chart===e.chart&&M.sdf(e,r.pose.position)<=0)};
function S(){const w=(C9.chapter2=C9.chapter2||{v:1});w.w3=w.w3||{cave:{visits:0,splash_t:-1e9,in:false},meteors:[],forecast:null,forecasts:0,riddle:{idx:0,tries:0},lantern:false,sleep:null,dreams:0,spring_s:0};return w.w3}
for(const [id,text] of Object.entries({sea_cave:'The tide drew back and let you into the sea cave.',bioluminescence:'You splashed, and the water lit up around your hands.',caught_by_the_tide:'The sea came in while you were inside; you swam for it.',island_stars:'The islands have the Star Deck\'s sky; you named what was up.',meteor:'A meteor, seen with your own eyes.',meteor_shower:'Eight or more in a minute: a shower night.',star_named:'You gave a star a name; everyone with your ledger sees it.',weather_prophet:'You said when the rain would come, and it came.',riddle_master:'Five riddles, five measurements, all right.',keepers_lantern:'The keeper\'s lantern: three meters of the Undercity are yours to see.',first_dream:'You slept, and your records came back as a dream.',hot_spring:'Ten seconds in the hot spring; your legs forgot the sea.',scratched:'You cut words into the dark.',wall_words:'In the dark your fingers found words another resident left.'}))CAT.register(id,text);

// Sea cave on the west shore of Hollow Isle: floor at about −0.6 m, so the sea rule opens it when the tide is below −0.3.
const CAVE=(()=>{let x=-540;const y=420;while(AR.h(x,y)>-.55&&x>-900)x-=2;return [x-4,y]})();
M.addEntity({id:'hollow.sea_cave',chart:ISLE,position:[CAVE[0],CAVE[1],1.2],shape:{kind:'VOLUME',halfExtents:[5,5,1.4]},tags:['cave','sea','secret','landmark'],collision:false,material:null,label:'sea cave',affordances:['splash']});
M.addEntity({id:'hollow.hot_spring',chart:ISLE,position:[-518,548,AR.h(-518,548)+.3],shape:{kind:'VOLUME',halfExtents:[2.5,2.5,.6]},tags:['spring','water','warm','landmark'],collision:false,material:'water',label:'hot spring',affordances:['bathe']});
SN.addSource({id:'plankton',chart:ISLE,pos:'hollow.sea_cave',label:'plankton light',sound:()=>0,light:()=>{const s=S().cave,r=me(),v=Math.hypot(r?.v?.[0]||0,r?.v?.[1]||0);return s.in?(.02+.3*v+(now()-s.splash_t<5?2*Math.exp(-(now()-s.splash_t)/2):0)):0}});
SN.addSource({id:'spring',chart:ISLE,pos:'hollow.hot_spring',label:'the hot spring',sound:()=>36,smell:{label:'sulfur and steam',S:()=>.7}});
function splash(){const s=S().cave;if(!s.in)return {ok:false,error:'NOT_IN_THE_WATER',hint:'the sea cave on the west shore of Hollow Isle, at low tide'};s.splash_t=now();CAT.discover('bioluminescence');return {ok:true,text:'You bring your hands down and the water answers: blue-green light runs out from them and fades in a breath.'}}
function swimOut(){const r=me(),s=S().cave;if(!r||!s.in)return {ok:false,error:'NOT_IN_THE_CAVE'};let x=CAVE[0],y=CAVE[1],k=0;while(AR.h(x,y)<LGM.tide().height_m+.4&&k++<60)x+=2;r.pose.position=[x,y,AR.h(x,y)+.85];r.v=[0,0,0];r.intent=null;M.bump();for(const z of ['leg.L.shin','leg.R.shin','leg.L.thigh','leg.R.thigh','torso.abdomen'])try{ATM.setThermal(z,'water',11,2,'SEA_SWIM','WORLD_GROUNDED')}catch(e){}return {ok:true,text:`You push off and swim ${(x-CAVE[0]).toFixed(0)} m to where the floor rises; the sea is 11 °C and keeps your legs for a while.`}}
function stepCave(dt){const r=me(),s=S().cave;if(!r||r.chart!==ISLE){s.in=false;return}const was=s.in;s.in=inside('hollow.sea_cave',r);if(s.in&&!was){s.visits++;CAT.discover('sea_cave')}if(s.in&&LGM.tide().height_m>.2){for(const z of ['leg.L.shin','leg.R.shin','foot.L.sole','foot.R.sole'])try{ATM.setThermal(z,'water',11,dt+.3,'SEA_FLOOD','WORLD_GROUNDED')}catch(e){}if(!s.flooded){s.flooded=true;CAT.discover('caught_by_the_tide')}}else if(!s.in)s.flooded=false;
 if(inside('hollow.hot_spring',r)){for(const z of ['leg.L.shin','leg.R.shin','leg.L.thigh','leg.R.thigh','foot.L.sole','foot.R.sole','pelvis.seat'])try{ATM.setThermal(z,'water',39,dt+.3,'HOT_SPRING','WORLD_GROUNDED')}catch(e){}S().spring_s+=dt;if(S().spring_s>=10)CAT.discover('hot_spring')}}

// The sky from the islands and the city: the Deck's constellations, the comet, meteors from a seeded channel.
const outdoors=()=>room()===ISLE||room()===CITY;
let meteorChan=null;const showerNight=()=>Math.floor(T()/600)%3===2;
function stepSky(){if(!outdoors()||!AR.isNight())return;if(!meteorChan)meteorChan=TL.channel(0x5ca1ab1e);const rate=showerNight()?.15:.012;for(const t of meteorChan.step(now(),rate)){S().meteors.push(+t.toFixed(2));while(S().meteors.length>200)S().meteors.shift()}}
function sky(){if(!outdoors())return {ok:false,error:'NO_SKY_HERE',hint:'the islands or the city'};if(!AR.isNight())return {ok:true,night:false,sun_alt_deg:+AR.sunAlt().toFixed(1),text:`Day; the sun is ${AR.sunAlt().toFixed(0)}° up. Stars after sunset.`};const st=CAT.state().sky,recent=S().meteors.filter(t=>now()-t<=60),names=starNames();CAT.discover('island_stars');if(recent.length)CAT.discover('meteor');if(recent.length>=8)CAT.discover('meteor_shower');
 return {ok:true,night:true,constellations:st.visible,comet:st.comet?.up?{alt:st.comet.alt,az:st.comet.az}:null,meteors_last_minute:recent.length,shower_night:showerNight(),named:names,text:`${st.visible.length?st.visible.join(', ')+' above the horizon':'Nothing you know above the horizon'}${st.comet?.up?`; the comet at ${st.comet.alt.toFixed(0)}°`:''}. ${recent.length?`${recent.length} meteor${recent.length===1?'':'s'} in the last minute${showerNight()?' (a shower night)':''}.`:showerNight()?'A shower night; wait and look again.':'No meteors in the last minute.'}${names.length?' Named: '+names.map(n=>`${n.name} in ${n.constellation}`).join(', ')+'.':''}`}}
function starNames(){const seen={};for(const e of records())if(e.kind==='NAME_STAR'&&typeof e.name==='string')seen[`${e.by}|${e.constellation}`]={constellation:e.constellation,name:e.name,by:handle(e.by),mine:mine(e)};return Object.values(seen)}
function nameStar(constellation,name){const c=String(constellation||'').toLowerCase().replace(/^the\s+/,'').trim(),cs=CAT.state().sky.visible.concat(['the lantern','the kite','the cat','the orrery','the well']).map(x=>x.replace(/^the\s+/,'')),k=cs.find(x=>x===c||x.startsWith(c));if(!k)return {ok:false,error:'WHICH_CONSTELLATION',constellations:[...new Set(cs)]};const nm=String(name||'').replace(/[^\w\s'-]/g,'').trim().slice(0,24);if(nm.length<2)return {ok:false,error:'NAME_IT'};if(!AR.isNight()||!outdoors())return {ok:false,error:'NAME_IT_UNDER_THE_STARS'};if(starNames().some(n=>n.mine&&n.constellation==='the '+k))return {ok:false,error:'ONE_NAME_PER_CONSTELLATION'};LG.record('NAME_STAR',{constellation:'the '+k,name:nm,wall:Date.now()});CAT.discover('star_named');return {ok:true,text:`The brightest star of ${'the '+k} is ${nm} now, in every world that carries your ledger.`}}

// Forecast: the band's phase at your feet is u − 3t (mod 2400), peak at 1200; it arrives in (phase − 1200)/3 s.
function forecast(){const r=me();if(!r||r.chart!==ISLE)return {ok:false,error:'FORECAST_FROM_THE_ISLANDS'};const [x,y]=r.pose.position,u=.6*x+.8*y,phase=((u-3*now())%2400+2400)%2400;const inS=phase>1200?(phase-1200)/3:(phase+1200)/3,width=260/3,s=S();s.forecasts++;s.forecast={t_peak:now()+inS,x,y,made:now()};return {ok:true,now:+AR.rain(x,y).toFixed(2),peak_in_s:Math.round(inS),rain_from_s:Math.max(0,Math.round(inS-width)),rain_to_s:Math.round(inS+width),text:`Rain here now ${Math.round(AR.rain(x,y)*100)}%. The band peaks over this spot in ${Math.round(inS)} s, wet from about ${Math.max(0,Math.round(inS-width))} s to ${Math.round(inS+width)} s. Fish bite less in the glare before it.`}}
function stepForecast(){const f=S().forecast;if(!f)return;if(Math.abs(now()-f.t_peak)<=15&&AR.rain(f.x,f.y)>.3){CAT.discover('weather_prophet');S().forecast=null}else if(now()>f.t_peak+120)S().forecast=null}

// The keeper's riddles: five measurements from five rooms. All five earn the lantern.
const RIDDLES=[{q:'How many steps climb the east tower to the roof?',a:30,tol:0,where:'Meridian City'},{q:'What is the lowest voice of the well, in hertz?',a:61.25,tol:1,where:'Resonance Well'},{q:'How deep is the Hollow from its mouth to its back wall, in meters?',a:47.3,tol:2.5,where:'Hollow Isle'},{q:'How long from high water to high water, in seconds?',a:300,tol:5,where:'the Archipelago'},{q:'How long is an island day, in seconds?',a:600,tol:5,where:'the Archipelago'}];
function riddle(){const s=S().riddle;if(s.idx>=RIDDLES.length)return {ok:true,done:true,text:'The keeper has no more riddles for you; the lantern is yours.'};const r=RIDDLES[s.idx];return {ok:true,number:s.idx+1,of:RIDDLES.length,question:r.q,text:`The keeper's notice, riddle ${s.idx+1} of ${RIDDLES.length}: "${r.q}" Answer with a number: answer <value>.`}}
function answer(v){const s=S().riddle;if(s.idx>=RIDDLES.length)return {ok:true,done:true,text:'All answered.'};const x=Number(v);if(!Number.isFinite(x))return {ok:false,error:'A_NUMBER'};s.tries++;const r=RIDDLES[s.idx];if(Math.abs(x-r.a)>r.tol)return {ok:true,correct:false,text:`${x}? The keeper shakes his head. Measure it, in ${r.where}.`};s.idx++;if(s.idx>=RIDDLES.length){CAT.discover('riddle_master');S().lantern=true;CAT.discover('keepers_lantern');return {ok:true,correct:true,done:true,text:'Right. The keeper hands you a brass lantern with a shuttered flame. In the dark it gives you three meters.'}}return {ok:true,correct:true,next:RIDDLES[s.idx].q,text:`Right. Next: "${RIDDLES[s.idx].q}"`}}
// The lantern changes what the dark allows: the Undercity's view radius becomes three meters while you carry it.
const under=M.charts()[UNDER];if(under)under.view=()=>S().lantern?3:.3;

// Dreams: lie down in the Nest at night and stay; a dream is made only from your own records.
function sleep(){const r=me();if(!r||room()!==NEST)return {ok:false,error:'SLEEP_IN_THE_NEST'};if(r.posture!=='lying')return {ok:false,error:'LIE_DOWN_FIRST'};if(!AR.isNight())return {ok:false,error:'NO_SLEEP_IN_DAYLIGHT',sun_alt_deg:+AR.sunAlt().toFixed(1),hint:'sunset in '+Math.round(((242.7-(T()%600))%600+600)%600)+' s'};S().sleep={t0:now()};return {ok:true,text:'You let the mattress have your weight. Stay sixty seconds and dream.'}}
function dream(){const sl=S().sleep;if(!sl)return {ok:false,error:'NOT_ASLEEP',hint:'sleep, lying in the Nest, at night'};if(now()-sl.t0<59.9)return {ok:true,asleep:true,remaining_s:Math.ceil(60-(now()-sl.t0)),text:`Not yet. ${Math.round(60-(now()-sl.t0))} s more.`};const scenes=[],vis=Object.keys(C9?.chapter2?.long?.visits||{}).filter(k=>k!==NEST),pet=window.REALITI_COMPANIONS_V1?.companion?.()?.companion,letters=records().filter(e=>e.kind==='LETTER'&&mine(e)),catches=records().filter(e=>e.kind==='CATCH'&&mine(e)),found=Object.entries(CAT.found()).sort((a,b)=>b[1].t-a[1].t).slice(0,2);
 if(vis.length)scenes.push({kind:'place',room:vis[vis.length-1],text:`You are in ${CT?.venues?window.REALITI_MATRIX_WORLD_V1?.title?.(vis[vis.length-1])||vis[vis.length-1]:vis[vis.length-1]} again, and it is empty.`});
 if(pet)scenes.push({kind:'companion',name:pet.name,text:`${pet.name} walks ahead of you for once and does not look back.`});
 if(letters.length)scenes.push({kind:'letter',to:letters[letters.length-1].to,text:`${letters[letters.length-1].to} is reading your letter aloud, but the words are the tide table.`});
 if(catches.length)scenes.push({kind:'catch',fish:catches[catches.length-1].fish,text:`The ${catches[catches.length-1].fish} is back in the water and larger.`});
 for(const [id] of found)scenes.push({kind:'discovery',id,text:id.replaceAll('_',' ')+', over and over.'});
 if(!scenes.length)scenes.push({kind:'empty',text:'Rain on a window. Nothing you have done yet.'});
 S().sleep=null;S().dreams++;CAT.discover('first_dream');return {ok:true,dreams:S().dreams,scenes,text:'You dreamed: '+scenes.map(s=>s.text).join(' ')}}

// Scratches in the dark: words cut where you stand, found by touch.
function scratch(text){const r=me();if(!r||r.chart!==UNDER)return {ok:false,error:'SCRATCH_IN_THE_DARK'};const t=String(text||'').replace(/\s+/g,' ').trim().slice(0,80);if(!t)return {ok:false,error:'WRITE_WHAT'};const touch=U.touch();if(!touch.touched?.some(x=>x.material&&!x.label))return {ok:false,error:'FIND_A_WALL_FIRST',hint:'touch until a wall is within reach'};LG.record('SCRATCH',{x:+r.pose.position[0].toFixed(1),y:+r.pose.position[1].toFixed(1),text:t,wall:Date.now()});CAT.discover('scratched');return {ok:true,text:`You cut it letter by letter: "${t}".`}}
function scratches(){const r=me();if(!r||r.chart!==UNDER)return [];const out=records().filter(e=>e.kind==='SCRATCH'&&Number.isFinite(e.x)&&Math.hypot(e.x-r.pose.position[0],e.y-r.pose.position[1])<=1.2).map(e=>({by:handle(e.by),mine:mine(e),text:e.text}));if(out.some(x=>!x.mine))CAT.discover('wall_words');return out}

let at=-1e9;const adv=b7Advance;b7Advance=function(dt){const r=adv(dt);const t=now(),d=Math.min(2,Math.max(0,t-at));if(d<.25)return r;at=t;try{stepCave(d);stepSky();stepForecast()}catch(e){}return r};
const actions0=b4AgentActions;b4AgentActions=function(){const a=actions0();const rm=room();if(rm===ISLE){if(S().cave.in)a.push({id:'splash',label:'SPLASH THE WATER'},{id:'swim_out',label:'SWIM OUT'});a.push({id:'forecast',label:'READ THE RAIN'})}if(outdoors()&&AR.isNight())a.push({id:'sky',label:'LOOK AT THE STARS'});if(rm===NEST&&AR.isNight()&&me()?.posture==='lying')a.push({id:S().sleep?'dream':'sleep',label:S().sleep?'DREAM':'SLEEP'});return a};
function receipt(type,res){C9.b4=C9.b4||{};C9.b4.lastReceipt={type,room:room(),narrative:res.text||(res.error?`You cannot: ${res.error}.`:''),...res,law:'tide, sky, rain and records are measured; narration reports them'};try{c9save()}catch(e){}return true}
const verb0=c9verb;c9verb=function(r,verb){const v=String(verb||'');const F={splash,swim_out:swimOut,forecast,sky,sleep,dream};if(F[v]&&(r===ISLE||r===CITY||r===NEST)){c9count(r,v);return receipt('W3_'+v.toUpperCase(),F[v]())}return verb0(r,verb)};
window.REALITI_WONDER3_V1=Object.freeze({version:'1.0',cave:cp(CAVE),splash,swimOut,sky,nameStar,starNames,forecast,riddle,answer,riddles:()=>RIDDLES.map(r=>r.q),lantern:()=>S().lantern,sleep,dream,scratch,scratches,state:()=>cp(S())});
})();
