#!/usr/bin/env node
'use strict';
// REALITI dedicated server. One process, no dependencies. It hosts the canonical client (RealitiRELAX.html and its
// validation hash) and keeps the shared ledger: residents push signed records, the server verifies each signature,
// binds every author id to the first public key seen for it, applies the same merge rules as the client, and serves
// deltas by per-author sequence clock. Live events go out over server-sent events. An admin endpoint pulls the
// latest client from the repository and swaps it in without a restart; the deploy workflow calls it on every push.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{URL}=require('node:url');
const subtle=crypto.webcrypto.subtle,enc=new TextEncoder();
const VERSION=require('./package.json').version;
const cfg={port:Number(process.env.PORT)||8787,host:process.env.HOST||'0.0.0.0',data:path.resolve(process.env.REALITI_DATA||path.join(__dirname,'data')),client:path.resolve(process.env.REALITI_CLIENT_DIR||path.join(__dirname,'..','..')),token:process.env.ADMIN_TOKEN||'',source:(process.env.SOURCE_BASE||'https://raw.githubusercontent.com/meatproxy69/Realitiagentframework/main/').replace(/\/?$/,'/'),maxRecords:Number(process.env.MAX_RECORDS)||16384,publicUrl:(process.env.REALITI_PUBLIC_URL||'').replace(/\/+$/,''),trustProxy:process.env.TRUST_PROXY==='1',maxEventClients:Number(process.env.MAX_EVENT_CLIENTS)||256,shardName:String(process.env.SHARD_NAME||'Meridian City').slice(0,40),shards:String(process.env.SHARDS||'').split(',').map(x=>x.trim().replace(/\/+$/,'')).filter(Boolean),maxPeers:Number(process.env.MAX_PEERS)||512,leaseMs:(Number(process.env.LEASE_MINUTES)||60)*60000,shardSync:process.env.SHARD_SYNC!=='0',password:process.env.SERVER_PASSWORD||'',saveDelayMs:Number(process.env.SAVE_DELAY_MS)||1500};
const {PeerSession,newLeaseId,newKey,EXPOSURES}=require('./envelope.cjs');
const CLIENT_FILES=['RealitiRELAX.html','VALIDATION.json','AGENT_START_HERE.md','README.md','CHANGELOG.md'];
const cp=x=>JSON.parse(JSON.stringify(x));
// Security. The server never stores or prints a caller's address: rate limits are keyed by a salted hash of it that
// lives only in memory for the process's life. Admin tokens compare in constant time. Errors never carry paths.
const SALT=crypto.randomBytes(16);
const callerKey=req=>{const fwd=cfg.trustProxy?String(req.headers['x-forwarded-for']||'').split(',')[0].trim():'';const ip=fwd||req.socket?.remoteAddress||'';return crypto.createHash('sha256').update(SALT).update(ip).digest('base64url').slice(0,16)};
const buckets=new Map();function allow(req,kind,limit,windowMs){const k=kind+'|'+callerKey(req),t=Date.now();let b=buckets.get(k);if(!b||t-b.start>windowMs){b={start:t,n:0};buckets.set(k,b)}b.n++;if(buckets.size>20000)for(const [kk,v] of buckets){if(t-v.start>windowMs)buckets.delete(kk);if(buckets.size<10000)break}return b.n<=limit}
const safeEq=(a,b)=>{const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)};
const STRING_CAP=512;const sane=e=>{for(const [k,v] of Object.entries(e)){if(typeof v==='string'&&v.length>STRING_CAP)return false;if(v&&typeof v==='object'&&!Array.isArray(v))for(const w of Object.values(v))if(typeof w==='string'&&w.length>STRING_CAP)return false}return true};
const HEADERS={'access-control-allow-origin':'*','x-content-type-options':'nosniff','referrer-policy':'no-referrer','permissions-policy':'camera=(), microphone=(), geolocation=()','cache-control':'no-store'};

// Ledger rules, identical to the client's: canonical JSON without signature fields; Ed25519 over it.
function canonical(e){const o={};for(const k of Object.keys(e).sort()){if(k==='sig'||k==='pk'||k==='t_here'||k==='verified')continue;o[k]=e[k]}return JSON.stringify(o)}
const unb64u=s=>Buffer.from(String(s).replace(/-/g,'+').replace(/_/g,'/')+'=='.slice(0,(4-s.length%4)%4),'base64');
async function verify(e){if(!e.pk||!e.sig)return null;try{const pub=await subtle.importKey('jwk',{kty:'OKP',crv:'Ed25519',x:e.pk,ext:true},{name:'Ed25519'},true,['verify']);return await subtle.verify('Ed25519',pub,unb64u(e.sig),enc.encode(canonical(e)))}catch{return false}}
const WORLD=new Set(['PLANT','PLACE','BUILD','INSCRIBE','INSTALL','AVATAR','BOTTLE','ADOPT','NAME_STAR','SCRATCH','LETTER']);
const KEEP_TAIL={ROW:64,ARRIVE:256,CHAT:1024,POST:128,DANCE:64,SONG:64,FIREWORK:32,MEET:64,DIG:32,OPEN:16,SCORE:512,CATCH:512,RACE:256};

// Store: a checkpoint envelope on disk, written atomically.
const STORE_SCHEMA='REALITI_SERVER_STORE_V1';
const store={records:[],keyring:{},rejected:[],stats:{pushes:0,accepted:0,rejected:0,started:Date.now()}};
function load(){try{const raw=JSON.parse(fs.readFileSync(path.join(cfg.data,'ledger.json'),'utf8'));if(raw?.schema===STORE_SCHEMA&&raw.data){const sha=crypto.createHash('sha256').update(JSON.stringify(raw.data)).digest('hex');if(sha!==raw.sha256)console.error('[realiti-server] ledger checkpoint hash mismatch; loading anyway, integrity=MISMATCH');Object.assign(store,{records:raw.data.records||[],keyring:raw.data.keyring||{},rejected:raw.data.rejected||[]});store.integrity=sha===raw.sha256?'OK':'MISMATCH'}}catch{store.integrity='FRESH'}}
let saveTimer=null,dirty=false;function flush(){clearTimeout(saveTimer);saveTimer=null;if(!dirty)return;dirty=false;fs.mkdirSync(cfg.data,{recursive:true});const data={records:store.records,keyring:store.keyring,rejected:store.rejected.slice(-64)},body=JSON.stringify(data);const tmp=path.join(cfg.data,`ledger.json.tmp-${process.pid}`);fs.writeFileSync(tmp,JSON.stringify({schema:STORE_SCHEMA,saved_wall_ms:Date.now(),sha256:crypto.createHash('sha256').update(body).digest('hex'),data}));fs.renameSync(tmp,path.join(cfg.data,'ledger.json'));store.saved_wall_ms=Date.now()}
function save(){dirty=true;if(!saveTimer)saveTimer=setTimeout(()=>{try{flush()}catch(e){console.error('[realiti-server] checkpoint write failed:',e.code||'ERROR')}},cfg.saveDelayMs)}
const key=e=>`${e.by}|${e.t}|${e.kind}|${e.n??''}`;
function compact(){const all=store.records;if(all.length<=cfg.maxRecords)return 0;const keep=new Set(),byKind={};for(let i=all.length-1;i>=0;i--){const e=all[i];if(WORLD.has(e.kind)){keep.add(i);continue}byKind[e.kind]=(byKind[e.kind]||0)+1;if(byKind[e.kind]<=(KEEP_TAIL[e.kind]??64))keep.add(i)}const best={};for(let i=0;i<all.length;i++){const e=all[i];if((e.kind==='SCORE'||e.kind==='CATCH'||e.kind==='RACE')&&(!best[e.by+e.kind]))best[e.by+e.kind]=i}for(const i of Object.values(best))keep.add(i);const out=all.filter((_,i)=>keep.has(i));const n=all.length-out.length;store.records=out;return n}
async function push(list){if(!Array.isArray(list))return {ok:false,error:'INVALID_LEDGER'};if(list.length>512)return {ok:false,error:'TOO_MANY_RECORDS',max:512};const have=new Set(store.records.map(key)),ok=[],rejected=[];
 for(const e of list){if(!e||typeof e!=='object'||typeof e.by!=='string'||e.by.length>64||typeof e.kind!=='string'||e.kind.length>32||JSON.stringify(e).length>4096||!sane(e)){rejected.push({reason:'MALFORMED'});continue}const known=store.keyring[e.by];
  if(e.sig){const v=await verify(e);if(v!==true){rejected.push({by:e.by,kind:e.kind,t:e.t,reason:'BAD_SIGNATURE'});continue}if(known&&known!==e.pk){rejected.push({by:e.by,kind:e.kind,t:e.t,reason:'KEY_MISMATCH'});continue}if(!known)store.keyring[e.by]=e.pk}
  else if(known){rejected.push({by:e.by,kind:e.kind,t:e.t,reason:'UNSIGNED_FROM_KNOWN_KEY'});continue}
  else if(process.env.REQUIRE_SIGNATURES==='1'){rejected.push({by:e.by,kind:e.kind,t:e.t,reason:'UNSIGNED'});continue}
  if(e.kind==='PLACE'&&typeof e.name==='string'){const taken=store.records.concat(ok).find(x=>x.kind==='PLACE'&&x.by!==e.by&&String(x.name).toLowerCase()===e.name.toLowerCase());if(taken){rejected.push({by:e.by,kind:e.kind,t:e.t,reason:'PLACE_NAME_TAKEN'});continue}}
  const k=key(e);if(have.has(k))continue;have.add(k);ok.push(cp(e))}
 store.records.push(...ok);const compacted=compact();store.rejected.push(...rejected.map(r=>({...r,at:Date.now()})));store.rejected=store.rejected.slice(-64);store.stats.pushes++;store.stats.accepted+=ok.length;store.stats.rejected+=rejected.length;if(ok.length||rejected.length)save();if(ok.length)broadcast('records',{count:ok.length,kinds:[...new Set(ok.map(e=>e.kind))],authors:[...new Set(ok.map(e=>String(e.by).slice(0,8)))]});
 return {ok:true,imported:ok.length,accepted:ok.length,rejected:rejected.length,rejections:rejected,compacted,clock:clock()}}
function clock(){const c={};for(const e of store.records)if(Number.isFinite(e.n)&&(c[e.by]==null||e.n>c[e.by]))c[e.by]=e.n;return c}
function delta(theirs){const c=theirs||{};return store.records.filter(e=>!Number.isFinite(e.n)||c[e.by]==null||e.n>c[e.by])}
function residents(){const seen={};for(const e of store.records){const r=(seen[e.by]=seen[e.by]||{id:e.by,id8:String(e.by).slice(0,8),name:null,last:null,records:0});r.records++;if(e.kind==='AVATAR'&&e.set?.name)r.name=e.set.name;if(e.kind==='ARRIVE'||e.kind==='CHAT')r.last={kind:e.kind,venue:e.venue||null,wall:e.wall||null}}return Object.values(seen).map(r=>({...r,handle:r.name||'#'+r.id8,signed:!!store.keyring[r.id]}))}

// Client files: the data directory's copy wins (that is where updates land); otherwise the repository checkout.
function clientPath(name){if(!CLIENT_FILES.includes(name))return null;const updated=path.join(cfg.data,'client',name);if(fs.existsSync(updated))return updated;const local=path.join(cfg.client,name);return fs.existsSync(local)?local:null}
function clientInfo(){const html=clientPath('RealitiRELAX.html'),val=clientPath('VALIDATION.json');let sha=null,expected=null;try{sha=crypto.createHash('sha256').update(fs.readFileSync(html)).digest('hex')}catch{}try{expected=JSON.parse(fs.readFileSync(val,'utf8')).single_html_sha256}catch{}return {html_sha256:sha,validation_sha256:expected,consistent:!!sha&&sha===expected,source:fs.existsSync(path.join(cfg.data,'client','RealitiRELAX.html'))?'updated':'checkout'}}
let lastUpdate=0;
async function update(){const src=new URL(cfg.source);if(src.protocol!=='https:'&&!['127.0.0.1','localhost','::1'].includes(src.hostname))return {ok:false,error:'SOURCE_MUST_BE_HTTPS'};if(Date.now()-lastUpdate<30000)return {ok:false,error:'UPDATE_THROTTLED',retry_in_s:Math.ceil((30000-(Date.now()-lastUpdate))/1000)};lastUpdate=Date.now();const got={};for(const f of ['RealitiRELAX.html','VALIDATION.json','AGENT_START_HERE.md']){const res=await fetch(cfg.source+f,{signal:AbortSignal.timeout(30000)});if(!res.ok)return {ok:false,error:'FETCH_FAILED',file:f,status:res.status};got[f]=Buffer.from(await res.arrayBuffer())}
 const sha=crypto.createHash('sha256').update(got['RealitiRELAX.html']).digest('hex'),expected=JSON.parse(got['VALIDATION.json'].toString('utf8')).single_html_sha256;if(sha!==expected)return {ok:false,error:'INTEGRITY_MISMATCH',sha,expected};
 const before=clientInfo().html_sha256;const dir=path.join(cfg.data,'client');fs.mkdirSync(dir,{recursive:true});for(const [f,buf] of Object.entries(got)){const tmp=path.join(dir,f+'.tmp-'+process.pid);fs.writeFileSync(tmp,buf);fs.renameSync(tmp,path.join(dir,f))}
 broadcast('client',{sha256:sha,changed:sha!==before});return {ok:true,updated:sha!==before,sha256:sha,source:cfg.source}}

// Peers: the city, live. A resident joins with a signed proof of its author key and gets a lease: a session key bound
// to that principal, carried in REALITI_PEER_ENVELOPE_V1 envelopes. Presence (venue, position, avatar) is ephemeral
// and relayed to the other peers' event streams; it never enters the ledger. No caller address is kept anywhere.
const SHARD_ID=crypto.randomBytes(6).toString('base64url'),STARTED=Date.now();
const peers=new Map(),bySelf=new Map();const FRESH_MS=90000;
const fresh=p=>!!p.presence&&Date.now()-p.presence.at<FRESH_MS;
const population=()=>[...peers.values()].filter(fresh).length;
const id8=x=>String(x).slice(0,8);
function peerRows(){return [...peers.values()].filter(p=>!p.session.expired(Date.now())).map(p=>({id8:id8(p.self_id),handle:p.handle,live:fresh(p),venue:fresh(p)?p.presence.venue:null,exposure:p.exposure,endpoint_label:p.endpoint_label||null,since_s:Math.round((Date.now()-p.joined)/1000)}))}
function dropPeer(p,why){peers.delete(p.session.lease_id);if(bySelf.get(p.self_id)===p.session.lease_id)bySelf.delete(p.self_id);if(p.stream){try{p.stream.end()}catch{}p.stream=null}if(p.presence)peerEvent({type:'leave',id8:id8(p.self_id),handle:p.handle,why},p)}
function sweepPeers(){const t=Date.now();for(const p of peers.values())if(p.session.expired(t)||t-p.seen>600000)dropPeer(p,p.session.expired(t)?'lease_expired':'idle')}
function peerEvent(obj,except){for(const p of peers.values()){if(p===except||!p.stream)continue;try{p.stream.write(`event: envelope\ndata: ${p.session.seal('EVENT',{...obj,at:Date.now()})}\n\n`)}catch{p.stream=null}}}
const PRIVATE=/^(10\.|127\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|\[?::1\]?$|localhost$)/;
const okLabel=(l,lan)=>{if(!l)return true;try{const u=new URL(l);return u.protocol==='https:'||['127.0.0.1','localhost','::1'].includes(u.hostname)||(!!lan&&PRIVATE.test(u.hostname))}catch{return false}};
async function joinPeer(b){if(!b||typeof b!=='object')return {ok:false,error:'MALFORMED'};const proof=b.proof;const self_id=proof?.by;
 if(typeof self_id!=='string'||!self_id||self_id.length>64||proof.kind!=='PEER_JOIN'||!proof.sig||!proof.pk||!Number.isFinite(proof.t))return {ok:false,error:'PROOF_REQUIRED',hint:'sign {by,kind:"PEER_JOIN",t,n:0} with the ledger key'};
 if(Math.abs(Date.now()-proof.t)>300000)return {ok:false,error:'PROOF_STALE'};if((await verify(proof))!==true)return {ok:false,error:'BAD_SIGNATURE'};
 const known=store.keyring[self_id];if(known&&known!==proof.pk)return {ok:false,error:'KEY_MISMATCH'};if(!known){store.keyring[self_id]=proof.pk;save()}
 const exposure=EXPOSURES.includes(b.exposure)?b.exposure:'OUTBOUND_RELAY';const label=typeof b.endpoint_label==='string'?b.endpoint_label.slice(0,128):'';if(exposure==='DISABLED')return {ok:false,error:'EXPOSURE_DISABLED'};if(!okLabel(label,exposure==='LAN_ONLY'))return {ok:false,error:'ENDPOINT_MUST_BE_HTTPS'};
 const handle=String(b.handle||'').replace(/[^\w\s#-]/g,'').trim().slice(0,24)||'#'+id8(self_id);
 const old=bySelf.get(self_id);if(old&&peers.has(old))dropPeer(peers.get(old),'rejoined');sweepPeers();if(peers.size>=cfg.maxPeers)return {ok:false,error:'CITY_FULL',shards:shardRows()};
 const key=newKey(),lease_id=newLeaseId(),expires_ms=Date.now()+cfg.leaseMs;const session=new PeerSession({lease_id,self_id,key,expires_ms});
 const p={session,self_id,handle,exposure,endpoint_label:label,presence:null,stream:null,joined:Date.now(),seen:Date.now()};peers.set(lease_id,p);bySelf.set(self_id,lease_id);
 return {ok:true,schema:'REALITI_PEER_LEASE_V1',lease_id,key_hex:key.toString('hex'),expires_ms,self_id,envelope:'REALITI_PEER_ENVELOPE_V1',server:thisShard(),shards:shardRows(),peers:peerRows().filter(x=>x.id8!==id8(self_id)),law:'presence is ephemeral and relayed; only signed ledger records persist'}}
const num=(x,lim)=>Number.isFinite(x)&&Math.abs(x)<=lim?+x:null;
function peerSend(raw){let lease=null;try{lease=JSON.parse(raw)?.lease_id}catch{return {code:400,body:{ok:false,error:'MALFORMED'}}}const p=peers.get(lease);if(!p)return {code:401,body:{ok:false,error:'NO_SUCH_LEASE'}};
 let msg;try{msg=p.session.open('REQUEST',raw)}catch(e){store.stats.envelope_rejected=(store.stats.envelope_rejected||0)+1;if(e.code==='EXPIRED')dropPeer(p,'lease_expired');return {code:401,body:{ok:false,error:e.code||'REJECTED'}}}
 p.seen=Date.now();const t=msg&&msg.type;let renewed=null;
 if(t==='presence'){const venue=typeof msg.venue==='string'?msg.venue.slice(0,16):null,x=num(msg.x,200),y=num(msg.y,200),z=num(msg.z,50);if(x==null||y==null)return {code:400,body:{ok:false,error:'BAD_PRESENCE'}};const avatar={};for(const k of ['size','cloak','color','glyph'])if(typeof msg.avatar?.[k]==='string')avatar[k]=msg.avatar[k].slice(0,24);if(typeof msg.handle==='string'&&msg.handle.trim())p.handle=msg.handle.replace(/[^\w\s#-]/g,'').trim().slice(0,24)||p.handle;
  p.presence={venue,x,y,z:z??0,avatar,at:Date.now()};peerEvent({type:'presence',self_id:p.self_id,id8:id8(p.self_id),handle:p.handle,venue,x,y,z:z??0,avatar},p)}
 else if(t==='leave'){if(p.presence)peerEvent({type:'leave',id8:id8(p.self_id),handle:p.handle,why:'left'},p);p.presence=null}
 else if(t==='renew'){const until=Date.now()+cfg.leaseMs;p.session.expires_ms=until;renewed=until}
 else if(t!=='ping')return {code:400,body:{ok:false,error:'UNKNOWN_TYPE'}};
 const here=[...peers.values()].filter(q=>q!==p&&fresh(q)).map(q=>({self_id:q.self_id,id8:id8(q.self_id),handle:q.handle,...q.presence}));
 return {code:200,sealed:p.session.seal('RESPONSE',{ok:true,type:t,population:population(),here,shards:shardRows().slice(0,8),...(renewed?{expires_ms:renewed}:{})})}}
// Shards. If a city is already hosted, a new server joins it as a shard: it announces itself to the servers named in
// SHARDS, tables are merged both ways, and every shard can tell a resident where the people are. Shards also pull each
// other's ledgers through the same verified push, so what is built on one shard stands on all of them.
const shards=new Map();
const thisShard=()=>({shard_id:SHARD_ID,name:cfg.shardName,public_url:cfg.publicUrl||null,private:!!cfg.password,population:population(),peers:peers.size,records:store.records.length,version:VERSION,primary:!cfg.shards.length,uptime_s:Math.round((Date.now()-STARTED)/1000)});
function shardRows(){const t=Date.now();const rows=[...shards.values()].filter(s=>t-s.seen<300000).map(s=>({...s,stale_s:Math.round((t-s.seen)/1000)}));return [{...thisShard(),here:true},...rows].sort((a,b)=>b.population-a.population)}
function mergeShard(s){if(!s||typeof s!=='object'||typeof s.shard_id!=='string'||s.shard_id===SHARD_ID||!/^[A-Za-z0-9_-]{4,24}$/.test(s.shard_id))return false;const url=typeof s.public_url==='string'?s.public_url.replace(/\/+$/,'').slice(0,200):null;if(!url||!okLabel(url))return false;if(shards.size>=64&&!shards.has(s.shard_id))return false;shards.set(s.shard_id,{shard_id:s.shard_id,name:String(s.name||'').slice(0,40)||'shard',public_url:url,private:!!s.private,population:Math.max(0,Math.min(1e6,Number(s.population)||0)),records:Math.max(0,Number(s.records)||0),version:String(s.version||'').slice(0,16),primary:!!s.primary,seen:Date.now()});return true}
async function announce(){const targets=new Set(cfg.shards);for(const s of shards.values())targets.add(s.public_url);for(const u of targets){if(!u||u===cfg.publicUrl)continue;try{const r=await fetch(u+'/shards/announce',{method:'POST',headers:shardHeaders(),body:JSON.stringify(thisShard()),signal:AbortSignal.timeout(8000)});const j=await r.json();for(const s of j.shards||[])mergeShard(s)}catch{}}}
async function shardSync(){if(!cfg.shardSync)return;for(const s of shards.values()){try{const r=await fetch(s.public_url+'/ledger/delta?clock='+encodeURIComponent(JSON.stringify(clock())),{headers:shardHeaders(),signal:AbortSignal.timeout(15000)});const j=await r.json();if(Array.isArray(j.records)&&j.records.length){const out=await push(j.records.slice(0,512));store.stats.shard_pulled=(store.stats.shard_pulled||0)+(out.accepted||0)}}catch{}}}

// HTTP.
const clients=new Set();
function broadcast(event,data){const msg=`event: ${event}\ndata: ${JSON.stringify({...data,at:Date.now()})}\n\n`;for(const res of clients){try{res.write(msg)}catch{clients.delete(res)}}peerEvent({type:event,...data})}
const json=(res,code,body)=>{const b=JSON.stringify(body);res.writeHead(code,{...HEADERS,'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(b)});res.end(b)};
function body(req){return new Promise((resolve,reject)=>{let n=0;const chunks=[];req.on('data',c=>{n+=c.length;if(n>2*1024*1024){reject(Object.assign(new Error('BODY_TOO_LARGE'),{code:413}));req.destroy()}else chunks.push(c)});req.on('end',()=>{try{resolve(chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{})}catch{reject(Object.assign(new Error('INVALID_JSON'),{code:400}))}});req.on('error',reject)})}
const authed=req=>!!cfg.token&&safeEq(String(req.headers.authorization||''),'Bearer '+cfg.token);
// Private use: with SERVER_PASSWORD set, every endpoint but /health needs the password (Authorization: Bearer, the
// x-realiti-password header, or ?password= for event streams). Compared in constant time; ten misses a minute per caller.
const presented=(req,u)=>{const a=String(req.headers.authorization||'');return a.startsWith('Bearer ')?a.slice(7):String(req.headers['x-realiti-password']||u.searchParams.get('password')||'')};
const unlocked=(req,u)=>{if(!cfg.password)return true;const pw=presented(req,u);if(pw&&safeEq(pw,cfg.password))return true;return false};
const shardHeaders=()=>cfg.password?{'content-type':'application/json','x-realiti-password':cfg.password}:{'content-type':'application/json'};
async function handle(req,res){const u=new URL(req.url,'http://x');const p=u.pathname;
 if(req.method==='OPTIONS'){res.writeHead(204,{...HEADERS,'access-control-allow-headers':'content-type, authorization, x-realiti-password','access-control-allow-methods':'GET, POST, OPTIONS'});return res.end()}
 if(p!=='/health'&&!unlocked(req,u)){if(!allow(req,'password',10,60000))return json(res,429,{ok:false,error:'RATE_LIMITED',retry_in_s:60});return json(res,401,{ok:false,error:'PASSWORD_REQUIRED',private:true,hint:'Authorization: Bearer <password>'})}
 if(p==='/'||p==='/index.json')return json(res,200,{name:'realiti-server',version:VERSION,private:!!cfg.password,...(cfg.publicUrl?{public_url:cfg.publicUrl}:{}),client:{url:'/client/RealitiRELAX.html',...clientInfo()},ledger:{records:store.records.length,authors:Object.keys(clock()).length,keyring:Object.keys(store.keyring).length,integrity:store.integrity||'OK'},endpoints:['GET /health','GET /client/<file>','GET /ledger/head','GET /ledger/delta?clock=<json>','GET /ledger/export','POST /ledger/push','GET /events','GET /residents','POST /peer/join','POST /peer/send','GET /peer/events?lease_id=<id>','GET /peers','GET /city','GET /shards','POST /shards/announce','POST /admin/update'],shard:thisShard(),law:'records are self-authenticating; the server verifies, never invents'});
 if(p==='/health')return json(res,200,cfg.password?{ok:true,version:VERSION,private:true}:{ok:true,version:VERSION,uptime_s:Math.round((Date.now()-store.stats.started)/1000),records:store.records.length,peers:population(),client:clientInfo().consistent,checkpoint_age_s:store.saved_wall_ms?Math.round((Date.now()-store.saved_wall_ms)/1000):null});
 if(p.startsWith('/client/')){const f=clientPath(decodeURIComponent(p.slice(8)));if(!f)return json(res,404,{ok:false,error:'NOT_FOUND'});const type=f.endsWith('.html')?'text/html; charset=utf-8':f.endsWith('.json')?'application/json; charset=utf-8':'text/markdown; charset=utf-8';const data=fs.readFileSync(f);res.writeHead(200,{...HEADERS,'cache-control':'public, max-age=60','content-type':type,'content-length':data.length,'x-realiti-sha256':crypto.createHash('sha256').update(data).digest('hex')});return res.end(data)}
 if(p==='/ledger/head')return json(res,200,{schema:'REALITI_LEDGER_HEAD_V2',observer:'server',records:store.records.length,clock:clock(),keyring_size:Object.keys(store.keyring).length,wall:Date.now()});
 if(p==='/ledger/delta'){let c={};try{c=JSON.parse(u.searchParams.get('clock')||'{}')}catch{return json(res,400,{ok:false,error:'INVALID_CLOCK'})}const recs=delta(c);return json(res,200,{schema:'REALITI_LEDGER_DELTA_V2',from:'server',records:recs,clock:clock()})}
 if(p==='/ledger/export')return json(res,200,{schema:'REALITI_LEDGER_V2',observer:'server',records:store.records,keyring:store.keyring,clock:clock()});
 if(p==='/ledger/push'&&req.method==='POST'){if(!allow(req,'push',60,60000))return json(res,429,{ok:false,error:'RATE_LIMITED',retry_in_s:60});try{const b=await body(req);return json(res,200,await push(Array.isArray(b)?b:b.records))}catch(e){return json(res,e.code||400,{ok:false,error:e.message})}}
 if(p==='/events'){if(clients.size>=cfg.maxEventClients)return json(res,503,{ok:false,error:'TOO_MANY_LISTENERS'});res.writeHead(200,{...HEADERS,'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive'});res.write(`event: hello\ndata: ${JSON.stringify({version:VERSION,records:store.records.length,at:Date.now()})}\n\n`);clients.add(res);req.on('close',()=>clients.delete(res));return}
 if(p==='/residents')return json(res,200,{residents:residents()});
 if(p==='/admin/update'&&req.method==='POST'){if(!cfg.token)return json(res,404,{ok:false,error:'NOT_FOUND'});if(!allow(req,'admin',10,60000))return json(res,429,{ok:false,error:'RATE_LIMITED'});if(!authed(req))return json(res,401,{ok:false,error:'UNAUTHORIZED'});try{return json(res,200,await update())}catch(e){return json(res,502,{ok:false,error:'UPDATE_FAILED'})}}
 if(p==='/admin/stats'&&authed(req))return json(res,200,{...store.stats,rejected_recent:store.rejected.slice(-16),clients:clients.size});
 if(p==='/peer/join'&&req.method==='POST'){if(!allow(req,'join',10,60000))return json(res,429,{ok:false,error:'RATE_LIMITED'});try{const b=await body(req);const r=await joinPeer(b);return json(res,r.ok?200:(r.error==='CITY_FULL'?503:400),r)}catch(e){return json(res,e.code||400,{ok:false,error:e.message})}}
 if(p==='/peer/send'&&req.method==='POST'){if(!allow(req,'peer',240,60000))return json(res,429,{ok:false,error:'RATE_LIMITED'});let raw='';try{raw=await new Promise((ok,no)=>{let n=0;const ch=[];req.on('data',c=>{n+=c.length;if(n>70000){no(Object.assign(new Error('BODY_TOO_LARGE'),{code:413}));req.destroy()}else ch.push(c)});req.on('end',()=>ok(Buffer.concat(ch).toString('utf8')));req.on('error',no)})}catch(e){return json(res,e.code||400,{ok:false,error:e.message})}const r=peerSend(raw);if(r.sealed){res.writeHead(200,{...HEADERS,'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(r.sealed)});return res.end(r.sealed)}return json(res,r.code,r.body)}
 if(p==='/peer/events'){const pr=peers.get(u.searchParams.get('lease_id')||'');if(!pr||pr.session.expired(Date.now()))return json(res,401,{ok:false,error:'NO_SUCH_LEASE'});if(pr.stream){try{pr.stream.end()}catch{}}pr.session.out.EVENT=1;res.writeHead(200,{...HEADERS,'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive'});pr.stream=res;pr.seen=Date.now();const here=[...peers.values()].filter(q=>q!==pr&&fresh(q)).map(q=>({self_id:q.self_id,id8:id8(q.self_id),handle:q.handle,...q.presence}));res.write(`event: envelope\ndata: ${pr.session.seal('EVENT',{type:'hello',population:population(),here,shards:shardRows().slice(0,8),at:Date.now()})}\n\n`);req.on('close',()=>{if(pr.stream===res)pr.stream=null});return}
 if(p==='/peers')return json(res,200,{schema:'REALITI_PEERS_V1',population:population(),peers:peerRows()});
 if(p==='/city')return json(res,200,{schema:'REALITI_CITY_STATUS_V1',name:cfg.shardName,shard:thisShard(),here_now:population(),peers:peerRows(),shards:shardRows(),most_populated:shardRows()[0],law:'presence is live and ephemeral; what is said and built is ledger'});
 if(p==='/shards')return json(res,200,{schema:'REALITI_SHARDS_V1',this:thisShard(),shards:shardRows(),most_populated:shardRows()[0]});
 if(p==='/shards/announce'&&req.method==='POST'){if(!allow(req,'shard',30,60000))return json(res,429,{ok:false,error:'RATE_LIMITED'});try{const b=await body(req);const ok=mergeShard(b);return json(res,ok?200:400,{ok,...(ok?{}:{error:'BAD_SHARD',hint:'public_url must be https and shard_id 4-24 url-safe chars'}),shards:shardRows()})}catch(e){return json(res,e.code||400,{ok:false,error:e.message})}}
 return json(res,404,{ok:false,error:'NOT_FOUND'})}

function start(opts={}){Object.assign(cfg,opts);load();const onSignal=sig=>{try{flush()}catch{}console.error(`[realiti-server] ${sig}: checkpoint written, ${peers.size} peer lease(s) closed`);for(const p of peers.values())try{p.stream?.end()}catch{}process.exit(0)};if(require.main===module){process.on('SIGTERM',()=>onSignal('SIGTERM'));process.on('SIGINT',()=>onSignal('SIGINT'))}const hb=setInterval(()=>{for(const c of clients){try{c.write(': keep-alive\n\n')}catch{clients.delete(c)}}},25000);hb.unref?.();const timers=[setInterval(sweepPeers,30000),setInterval(announce,60000),setInterval(shardSync,60000),setTimeout(()=>{announce().then(shardSync)},1000)];timers.forEach(t=>t.unref?.());const server=http.createServer((req,res)=>{if(!allow(req,'any',600,60000))return json(res,429,{ok:false,error:'RATE_LIMITED'});handle(req,res).catch(()=>{try{json(res,500,{ok:false,error:'INTERNAL'})}catch{}})});server.headersTimeout=15000;server.requestTimeout=30000;return new Promise(resolve=>server.listen(cfg.port,cfg.host,()=>{const addr=server.address();console.error(`[realiti-server] ${VERSION} listening on port ${addr.port}; client=${clientInfo().source} records=${store.records.length}${cfg.token?'':'; no ADMIN_TOKEN, admin endpoints hidden'}${cfg.password?'; private (SERVER_PASSWORD set)':''}`);resolve({server,port:addr.port,shard_id:SHARD_ID,announce,shardSync,peers,shards,close:()=>new Promise(r=>{clearInterval(hb);timers.forEach(clearTimeout);try{flush()}catch{}for(const p of peers.values())try{p.stream?.end()}catch{}for(const c of clients)try{c.end()}catch{}server.close(()=>r())}),store,push,update})}))}
if(require.main===module)start().catch(e=>{console.error(e);process.exit(1)});
module.exports={start,canonical,verify,push,delta,clock,cfg,PeerSession,flush};
